.TH DAT2GMT 1 "Feb 27 2014" "GMT 4.5.13 (SVN)" "Generic Mapping Tools"
.SH NAME
dat2gmt \- Convert an ASCII file to a binary gmt file
.SH SYNOPSIS
\fBdat2gmt\fP \fIgmtfile\fP
.SH DESCRIPTION
\fBdat2gmt\fP reads an ASCII version of a gmt file (made by \fBgmt2dat\fP) from standard
input and creates a binary gmt file.
.SH EXAMPLES
To create a gmt file from the ASCII file c2104_fixed.ascii, run
.br
.sp
\fBdat2gmt\fP c2104_fixed.ascii c2104.gmt
.SH "SEE ALSO"
.IR gmt2dat (1),
.IR GMT (1)
.SH REFERENCES
Wessel, P., and W. H. F. Smith, 2014, The Generic Mapping Tools (GMT) version
4.5.12 Technical Reference & Cookbook, SOEST/NOAA.
.br
Wessel, P., and W. H. F. Smith, 1998, New, Improved Version of Generic Mapping
Tools Released, EOS Trans., AGU, 79 (47), p. 579.
.br
Wessel, P., and W. H. F. Smith, 1995, New Version of the Generic Mapping Tools
Released, EOS Trans., AGU, 76 (33), p. 329.
.br
Wessel, P., and W. H. F. Smith, 1995, New Version of the Generic Mapping Tools
Released, http://www.agu.org/eos_elec/95154e.html, Copyright 1995 by the
American Geophysical Union.
.br
Wessel, P., and W. H. F. Smith, 1991, Free Software Helps Map and Display Data,
EOS Trans., AGU, 72 (41), p. 441.
.br
