.TH X2SYS_REPORT 1 "15 Jul 2011" "GMT 4.5.7" "Generic Mapping Tools"
.SH NAME
x2sys_report \- Report statistics from crossover data base
.SH SYNOPSIS
\fBx2sys_report\fP \fB\-C\fP\fIcolumn\fP \fB\-T\fP\fITAG\fP [ \fIcoedbase.txt\fP ] [ \fB\-A\fP ] 
[ \fB\-I\fP[\fIlist\fP] ] [ \fB\-L\fP[\fIcorrtable\fP] ] [ \fB\-N\fP\fInx_min\fP ] [ \fB\-Qe\fP|\fBi\fP ] 
[ \fB\-R\fP\fIwest\fP/\fIeast\fP/\fIsouth\fP/\fInorth\fP[\fBr\fP] ] [ \fB\-S\fP\fItrack\fP ] [ \fB\-V\fP ]
.SH DESCRIPTION
\fBx2sys_report\fP will read the input crossover ASCII data base \fIcoedbase.txt\fP (or \fIstdin\fP)
and report on the statistics of crossovers (\fIn, mean, stdev, rms, weight\fP) for each track.  Options are
available to let you exclude tracks and limit the output.
.TP
\fB\-C\fP
Specify which data column you want to process.  Crossovers related to this column name must be
present in the crossover data base.
.TP
\fB\-T\fP
Specify the x2sys \fITAG\fP which tracks the attributes of this data type.
.SH OPTIONS
No space between the option flag and the associated arguments.
.TP
.I coedbase.txt
The name of the input ASCII crossover error data base as produced by \fBx2sys_cross\fP.
If not given we read standard input instead.
.TP
\fB\-A\fP
Eliminate COEs by distributing the COE between the two tracks in proportion to track weight and producing
(dist, adjustment) spline knots files for each track (for the selected \fIcolumn\fP).  Such adjustments
may be used by \fBx2sys_datalist\fP.  The adjustment files are called \fItrack.column\fP.adj and are
placed in the \fB$X2SYS_HOME\fP/\fITAG\fP directory. For background information on how these adjustments
are designed, see \fIMittal\fP [1984].
.TP
\fB\-I\fP
Name of ASCII file with a list of track names (one per record) that should be excluded from consideration
[Default includes all tracks].
.TP
\fB\-L\fP
Apply optimal corrections to the chosen observable.  Append the correction
table to use [Default uses the correction table \fITAG\fP_corrections.txt which is expected to reside
in the \fB$X2SYS_HOME\fP/\fITAG\fP directory].
For the format of this file, see \fBx2sys_solve\fP.
.TP
\fB\-N\fP
Only report data from tracks involved in at least \fInx_min\fP crossovers [all tracks].
.TP
\fB\-Q\fP
Append \fBe\fP for external crossovers or \fBi\fP for internal crossovers only [Default is external].
.TP
\fB\-R\fP
\fIwest, east, south,\fP and \fInorth\fP specify the Region of interest, and you may specify them
in decimal degrees or in [+-]dd:mm[:ss.xxx][W|E|S|N] format.  Append \fBr\fP if lower left and upper right
map coordinates are given instead of w/e/s/n.  The two shorthands \fB\-Rg\fP and \fB\-Rd\fP stand for global domain
(0/360 and -180/+180 in longitude respectively, with -90/+90 in latitude). Alternatively, specify the name
of an existing grid file and the \fB\-R\fP settings (and grid spacing, if applicable) are copied from the grid.
For Cartesian data just give \fIxmin/xmax/ymin/ymax\fP.  This option bases the statistics
on those COE that fall inside the specified domain.
.TP
\fB\-S\fP
Name of a single track.  If given we restrict output to those crossovers involving this track [Default
output is crossovers involving any track pair].
.TP
\fB\-V\fP
Selects verbose mode, which will send progress reports to stderr [Default runs "silently"].
.SH EXAMPLES
To report statistics of all the external magnetic crossovers associated with the tag MGD77 from the file COE_data.txt,
restricted to occupy a certain region in the south Pacific, try
.br
.sp
\fBx2sys_report\fP COE_data.txt \fB\-V\fP \fB\-T\fPMGD77 \fB\-R\fP180/240/-60/-30 \fB\-C\fPmag > mag_report.txt
.br
.sp
To report on the faa crossovers globally that involves track 12345678, try
.br
.sp
\fBx2sys_report\fP COE_data.txt \fB\-V\fP \fB\-T\fPMGD77 \fB\-C\fPfaa \fB\-S\fP12345678  > faa_report.txt
.SH REFERENCES
Mittal, P. K. (1984), Algorithm for error adjustment of potential field data along a survey network, \fIGeophysics, 49\fP(4), 467-469.
.SH "SEE ALSO"
.IR x2sys_binlist (1)
.IR x2sys_cross (1)
.IR x2sys_datalist (1)
.IR x2sys_get (1)
.IR x2sys_init (1)
.IR x2sys_list (1)
.IR x2sys_put (1)
.IR x2sys_solve (1)
