.TH SPHTRIANGULATE 1 "5 Nov 2013" "GMT 4.5.11" "Generic Mapping Tools"
.SH NAME
sphtriangulate \- Perform optimal Delaunay triangulation or Voronoi construction of spherical data
.SH SYNOPSIS
\fBsphtriangulate\fP \fIinfiles\fP [ \fB\-A\fP ] [ \fB\-C\fP ] [ \fB\-D\fP ] [ \fB\-H\fP[\fBi\fP][\fInrec\fP] ] [ \fB\-L\fP\fIunit\fP ] 
[ \fB\-N\fP\fInfile\fP ] [ \fB\-Q\fP\fBd\fP|\fBv\fP ] [ \fB\-T\fP ] [ \fB\-V\fP ] [ \fB\-:\fP[\fBi\fP|\fBo\fP] ] [ \fB\-b\fP[\fBi\fP|\fBo\fP][\fBs\fP|\fBS\fP|\fBd\fP|\fBD\fP[\fIncol\fP]|\fBc\fP[\fIvar1\fP\fB/\fP\fI...\fP]] ] [ \fB\-m\fP[\fBi\fP|\fBo\fP][\fIflag\fP] ]
.SH DESCRIPTION
\fBsphtriangulate\fP reads one or more ASCII [or binary] files (or standard input) containing lon, lat and
performs a spherical Delaunay triangulation, i.e., it find how the points should be connected to give
the most equilateral triangulation possible on the sphere.  Optionally, you may choose \fB\-Qv\fP which
will do further processing to obtain the Voronoi polygons.  Normally, either set of polygons will
be written as fillable multi-segment output; use \fB\-T\fP to write unique arcs instead.
As an option, compute the area of each triangle or polygon.  The algorithm used is STRIPACK.
.TP
\fIinfiles\fP
Data files with the point coordinates in ASCII (or binary; see \fB\-b\fP).  If no files are given the standard input is read.
.SH OPTIONS
.TP
.B \-A
Compute the area of the spherical triangles (\fB\-Qd\fP) or polygons (\fB\-Qv\fP) and write the areas (in chosen
units; see \fB\-L\fP) in the multisegment output headers [no areas calculated].
.TP
.B \-C
For large data set you can save some memory (at the expense of more processing) by only storing one form of
location coordinates (geographic or Cartesian 3-D vectors) at any given time, translating from one form to
the other when necessary [Default keeps both arrays in memory].
.TP
.B \-D
Used with \fB\-m\fP to skip the last (repeated) input vertex at the end of a closed segment if it
equals the first point in the segment.  Requires \fB\-m\fP [Default uses all points].
.TP
\fB\-H\fP
Input file(s) has header record(s).  If used, the default number of header records is \fBN_HEADER_RECS\fP.
Use \fB\-Hi\fP if only input data should have header records [Default will write out header records if the
input data have them]. Blank lines and lines starting with # are always skipped.
.TP
.B \-L
Specify the unit used for distance and area calculations.  Choose among \fBe\fP (m), \fBk\fP (km), \fBm\fP (mile),
\fBn\fP (nautical mile), or \fBd\fP (spherical degree).  A spherical approximation is used unless
\fBELLIPSOID\fP is set to an actual ellipsoid.  When degree is selected the areas are given in steradians.
.TP
.B \-N
Write the information pertaining to each polygon (for Delaunay: the three node number and the triangle area;
for Voronoi the unique node lon, lat and polygon area) to a separate file [Default puts this information in
the segment headers of the output file].  Required if binary output is needed.
.TP
.B \-Q
Select between BD(d)elaunay or BD(v)oronoi mode [Delaunay].
.TP
.B \-T
Write the unique arcs of the construction [Default writes fillable triangles or polygons].
When used with \fB\-A\fP we store arc length in the segment header in chosen unit (see \fB\-L\fP).
.TP
\fB\-V\fP
Selects verbose mode, which will send progress reports to stderr [Default runs "silently"].
.TP
\fB\-:\fP
Toggles between (longitude,latitude) and (latitude,longitude) input and/or output.  [Default is (longitude,latitude)].
Append \fBi\fP to select input only or \fBo\fP to select output only.  [Default affects both].
.TP
\fB\-bi\fP
Selects binary input.
Append \fBs\fP for single precision [Default is \fBd\fP (double)].
Uppercase \fBS\fP or \fBD\fP will force byte-swapping.
Optionally, append \fIncol\fP, the number of columns in your binary input file
if it exceeds the columns needed by the program.
Or append \fBc\fP if the input file is netCDF. Optionally, append \fIvar1\fP\fB/\fP\fIvar2\fP\fB/\fP\fI...\fP to
specify the variables to be read.
[Default is 2 input columns].
.TP
\fB\-bo\fP
Selects binary output.
Append \fBs\fP for single precision [Default is \fBd\fP (double)].
Uppercase \fBS\fP or \fBD\fP will force byte-swapping.
Optionally, append \fIncol\fP, the number of desired columns in your binary output file.
[Default is same as input].
.TP
\fB\-m\fP
Multiple segment file(s).  Segments are separated by a special record.
For ASCII files the first character must be \fIflag\fP [Default is '>'].
For binary files all fields must be NaN and \fB\-b\fP must
set the number of output columns explicitly.  By default the \fB\-m\fP
setting applies to both input and output.  Use \fB\-mi\fP and \fB\-mo\fP
to give separate settings to input and output.
.SH ASCII FORMAT PRECISION
The ASCII output formats of numerical data are controlled by parameters in
your \.gmtdefaults4 file.  Longitude and latitude are formatted according to
\fBOUTPUT_DEGREE_FORMAT\fP, whereas other values are formatted according
to \fBD_FORMAT\fP.  Be aware that the format in effect can lead to loss of
precision in the output, which can lead to various problems downstream.  If
you find the output is not written with enough precision, consider switching
to binary output (\fB\-bo\fP if available) or specify more decimals using
the \fBD_FORMAT\fP setting.
.SH GRID VALUES PRECISION
Regardless of the precision of the input data, GMT programs that create
grid files will internally hold the grids in 4-byte floating point
arrays.  This is done to conserve memory and furthermore most if not all
real data can be stored using 4-byte floating point values.  Data with
higher precision (i.e., double precision values) will lose that precision
once GMT operates on the grid or writes out new grids.  To limit loss
of precision when processing data you should always consider normalizing
the data prior to processing.
.SH EXAMPLES
To triangulate the points in the file testdata.txt, and
make a Voronoi diagram via \fBpsxy\fP, use
.br
.sp
\fBsphtriangulate\fP testdata.txt \fB\-Qv\fP | psxy \fB\-Rg \-JG\fP30/30/6i \fB\-M \-L \-P \-W\fP1p \fB\-B\fP0g30 | gv \-
.br
.sp
To compute the optimal Delaunay triangulation network based on the multiple segment file globalnodes.d
and save the area of each triangle in the header record, try
.br
.sp
\fBsphtriangulate\fP globalnodes.d \fB\-M \-Qd \-A\fP > global_tri.d
.SH "SEE ALSO"
.IR GMT (1),
.IR triangulate (1)
.IR sphinterpolate (1)
.IR sphdistance (1)
.SH REFERENCES
Renka, R, J., 1997, Algorithm 772: STRIPACK: Delaunay Triangulation and Voronoi Diagram on the Surface of a Sphere, 
\fIAMC Trans. Math. Software, 23\fP (3), 416\-434.
