.TH GMTCONVERT 1 "5 Nov 2013" "GMT 4.5.11" "Generic Mapping Tools"
.SH NAME
gmtconvert \- Converts, Pastes, and/or Extracts columns from ASCII and binary 1-D tables
.SH SYNOPSIS
\fBgmtconvert\fP [ \fIinputfiles\fP ] [ \fB\-A\fP ] [ \fB\-D\fP[\fItemplate\fP] ] [ \fB\-E\fP[\fBf\fP|\fBl\fP] ] 
[ \fB\-F\fP\fIcols\fP ] [ \fB\-H\fP[\fBi\fP][\fInrec\fP] ] [ \fB\-L\fP ] [ \fB\-I\fP ] [ \fB\-N\fP ] 
[ \fB\-S\fP[\fB~\fP]\fI"search string"\fP ] [ \fB\-V\fP ] [ \fB\-:\fP[\fBi\fP|\fBo\fP] ] [ \fB\-b\fP[\fBi\fP|\fBo\fP][\fBs\fP|\fBS\fP|\fBd\fP|\fBD\fP[\fIncol\fP]|\fBc\fP[\fIvar1\fP\fB/\fP\fI...\fP]] ] 
[ \fB\-f\fP[\fBi\fP|\fBo\fP]\fIcolinfo\fP ] [ \fB\-g\fP[\fBa\fP]\fBx\fP|\fBy\fP|\fBd\fP|\fBX\fP|\fBY\fP|\fBD\fP|[\fIcol\fP]\fBz\fP[+|-]\fIgap\fP[\fBu\fP] ] [ \fB\-m\fP[\fBi\fP|\fBo\fP][\fIflag\fP] ]
.SH DESCRIPTION
\fBgmtconvert\fP reads its standard input [or inputfiles] and writes out
the desired information to standard output.  It can do a combination of
three things: (1) convert between binary and ASCII data tables, (2) paste
corresponding records from multiple files into a single file, (3)
extract a subset of the columns, (4) only extract segments whose header
matches a text pattern search, (5) just list all multisegment headers and no data
records, and (6) extract first and last data record for each segment.  Input (and hence output) may have multiple
subheaders if \fB\-m\fP is selected, and ASCII tables may have regular headers as well.
.TP
\fIdatafile(s)\fP
ASCII (or binary, see \fB\-bi\fP) file(s) holding a number of data columns. 
.SH OPTIONS
.TP
\fB\-A\fP
The records from the input files should be pasted horizontally, not appended vertically.  [Default
processes one file at the time].  Note for binary input, all the files you want to paste must
have the same number of columns (as set with \fB\-bi\fP).
.TP
\fB\-D\fP
For multiple segment data, dump each segment to a separate output file [Default writes a multiple segment
file to stdout].  Append a format template for the individual file names; this template \fBmust\fP contain a
C format specifier that can format an integer argument (the segment number); this is usually %d but could
be %8.8d which gives leading zeros, etc. [Default is gmtconvert_segment_%d.d].
.TP
\fB\-E\fP
Only extract the first and last record for each segment of interest [Default extracts
all records].  Optionally, append \fBf\fP or \fBl\fP to only extract the first or last
record of each segment, respectively.
.TP
\fB\-F\fP
Give a comma-separated list of desired columns or ranges (0 is first column) [Default outputs all columns].
.TP
\fB\-H\fP
Input file(s) has header record(s).  If used, the default number of header records is \fBN_HEADER_RECS\fP.
Use \fB\-Hi\fP if only input data should have header records [Default will write out header records if the
input data have them]. Blank lines and lines starting with # are always skipped.
.TP
\fB\-I\fP
Invert the order of rows, i.e., output the final records in reverse order, starting with the last and ending
up with the first input row [Default goes forward].
.TP
\fB\-L\fP
Only output a listing of all multisegment header records and no data records (requires \fB\-m\fP and ASCII data).
.TP
\fB\-N\fP
Do not write records that only contain NaNs in every field [Default writes all records].
.TP
\fB\-S\fP
Only output those segments whose header record contains the specified text string.  To reverse the search,
i.e., to output segments whose headers do \fInot\fP contain the specified pattern, use \fB\-S~\fP.
Should your pattern happen to start with ~ you need to escape this character with a backslash \ [Default output all segments].
.TP
\fB\-V\fP
Selects verbose mode, which will send progress reports to stderr [Default runs "silently"].
.TP
\fB\-:\fP
Toggles between (longitude,latitude) and (latitude,longitude) input and/or output.  [Default is (longitude,latitude)].
Append \fBi\fP to select input only or \fBo\fP to select output only.  [Default affects both].
.TP
\fB\-bi\fP
Selects binary input.
Append \fBs\fP for single precision [Default is \fBd\fP (double)].
Uppercase \fBS\fP or \fBD\fP will force byte-swapping.
Optionally, append \fIncol\fP, the number of columns in your binary input file
if it exceeds the columns needed by the program.
Or append \fBc\fP if the input file is netCDF. Optionally, append \fIvar1\fP\fB/\fP\fIvar2\fP\fB/\fP\fI...\fP to
specify the variables to be read.
.TP
\fB\-bo\fP
Selects binary output.
Append \fBs\fP for single precision [Default is \fBd\fP (double)].
Uppercase \fBS\fP or \fBD\fP will force byte-swapping.
Optionally, append \fIncol\fP, the number of desired columns in your binary output file.
[Default is same as input].
.TP
\fB\-f\fP
Special formatting of input and/or output columns (time or geographical data).
Specify \fBi\fP or \fBo\fP to make this apply only to input or output [Default applies to both].
Give one or more columns (or column ranges) separated by commas.
Append \fBT\fP (absolute calendar time), \fBt\fP (relative time in chosen \fBTIME_UNIT\fP since \fBTIME_EPOCH\fP),
\fBx\fP (longitude), \fBy\fP (latitude), or \fBf\fP (floating point) to each column
or column range item.  Shorthand \fB\-f\fP[\fBi\fP|\fBo\fP]\fBg\fP means \fB\-f\fP[\fBi\fP|\fBo\fP]0\fBx\fP,1\fBy\fP
(geographic coordinates).
.TP
\fB\-g\fP
Examine the spacing between consecutive data points in order to impose breaks in the line.
Append \fBx\fP|\fBX\fP or \fBy\fP|\fBY\fP to define a gap when there is a large enough change in the x or y coordinates, respectively,
or \fBd\fP|\fBD\fP for distance gaps; use upper case to calculate gaps from projected coordinates.  For gap-testing on other columns
use [\fIcol\fP]\fBz\fP; if \fIcol\fP is not prepended the it defaults to 2 (i.e., 3rd column).
Append [+|-]\fIgap\fP and optionally a unit \fBu\fP.  Regarding optional signs: -ve means previous minus current column value must exceed
|\fIgap\fP to be a gap, +ve means current minus previous column value must exceed \fIgap\fP, and no sign means the absolute value of the
difference must exceed \fIgap\fP.
For geographic data (\fBx\fP|\fBy\fP|\fBd\fP), the unit \fBu\fP may be m\fBe\fPter [Default], \fBk\fPilometer, \fBm\fPiles, or \fBn\fPautical miles.
For projected data (\fBX\fP|\fBY\fP|\fBD\fP), choose from \fBi\fPnch, \fBc\fPentimeter, \fBm\fPeter, or \fBp\fPoints [Default unit set by MEASURE_UNIT].
Note: For \fBx\fP|\fBy\fP|\fBz\fP with time data the unit is instead controlled by TIME_UNIT.
Repeat the option to specify multiple criteria, of which any can be met to produce a line break.
Issue an additional \fB\-ga\fP to indicate that all criteria must be met instead.
.TP
\fB\-m\fP
Multiple segment file(s).  Segments are separated by a special record.
For ASCII files the first character must be \fIflag\fP [Default is '>'].
For binary files all fields must be NaN and \fB\-b\fP must
set the number of output columns explicitly.  By default the \fB\-m\fP
setting applies to both input and output.  Use \fB\-mi\fP and \fB\-mo\fP
to give separate settings to input and output.
.SH ASCII FORMAT PRECISION
The ASCII output formats of numerical data are controlled by parameters in
your \.gmtdefaults4 file.  Longitude and latitude are formatted according to
\fBOUTPUT_DEGREE_FORMAT\fP, whereas other values are formatted according
to \fBD_FORMAT\fP.  Be aware that the format in effect can lead to loss of
precision in the output, which can lead to various problems downstream.  If
you find the output is not written with enough precision, consider switching
to binary output (\fB\-bo\fP if available) or specify more decimals using
the \fBD_FORMAT\fP setting.
.SH EXAMPLES
To convert the binary file test.b (single precision) with 4 columns to ASCII:
.br
.sp
\fBgmtconvert\fP test.b \fB\-bis\fP 4 > test.dat
.br
.sp
To convert the multiple segment ASCII table test.d to a double precision binary file:
.br
.sp
\fBgmtconvert\fP test.d \fB\-m\fP \fB\-bo\fP > test.b
.br
.sp
You have an ASCII table with 6 columns and you want to plot column 5 versus column 0.  Try
.br
.sp
\fBgmtconvert\fP table.d \fB\-F\fP 5,0 | psxy ...
.br
.sp
If the file instead is the binary file results.b which has 9 single-precision values per record,
we extract the last column and columns 4-6 and write ASCII with the command
.br
.sp
\fBgmtconvert\fP results.b \fB\-F\fP 8,4-6 -bi9s | psxy ...
.br
.sp
You want to plot the 2nd column of a 2-column file left.d versus the first column of a file right.d:
.br
.sp
\fBgmtconvert\fP left.d right.d \fB\-A\fP \fB\-F\fP 1,2 | psxy ...
.br
.sp
To extract all segments in the file big_file.d whose headers contain the string "RIDGE AXIS", try
.br
.sp
\fBgmtconvert\fP big_file.d \fB\-m\fP \fB\-S\fP"RIDGE AXIS" > subset.d
.br
.SH "SEE ALSO"
.IR GMT (1),
.IR minmax (1)
