#!/bin/sh
#
#	$Id: gmtget 9545 2011-07-27 19:31:54Z pwessel $
#
#	gmtget - Return the current setting of the specified parameter
#
if [ ${#} -ne 1 ]; then
	echo "usage: gmtget PARAMETER" >&2
	exit -1
fi
gmtdefaults -L | grep "^${1}	" | awk '{print $3}'
