/* grdreformat.h	[Created by src/GNUmakefile] */
#define N_GRDTXT_LINES 35
	char *grd_formats[N_GRDTXT_LINES] = {
		"----------------------------------------------------------------",
		"| ID | DESCRIPTION - GMT 3 netCDF legacy formats               |",
		"----------------------------------------------------------------",
		"| cb | GMT netCDF format (byte) (deprecated)                   |",
		"| cs | GMT netCDF format (short) (deprecated)                  |",
		"| ci | GMT netCDF format (int) (deprecated)                    |",
		"| cf | GMT netCDF format (float) (deprecated)                  |",
		"| cd | GMT netCDF format (double) (deprecated)                 |",
		"----------------------------------------------------------------",
		"| ID | DESCRIPTION - GMT native binary formats                 |",
		"----------------------------------------------------------------",
		"| bm | GMT native, C-binary format (bit-mask)                  |",
		"| bb | GMT native, C-binary format (byte)                      |",
		"| bs | GMT native, C-binary format (short)                     |",
		"| bi | GMT native, C-binary format (int)                       |",
		"| bf | GMT native, C-binary format (float)                     |",
		"| bd | GMT native, C-binary format (double)                    |",
		"----------------------------------------------------------------",
		"| ID | DESCRIPTION - GMT 4 netCDF standard                     |",
		"----------------------------------------------------------------",
		"| nb | GMT netCDF format (byte)   (COARDS-compliant)           |",
		"| ns | GMT netCDF format (short)  (COARDS-compliant)           |",
		"| ni | GMT netCDF format (int)    (COARDS-compliant)           |",
		"| nf | GMT netCDF format (float)  (COARDS-compliant) [DEFAULT] |",
		"| nd | GMT netCDF format (double) (COARDS-compliant)           |",
		"----------------------------------------------------------------",
		"| ID | DESCRIPTION - Misc formats                              |",
		"----------------------------------------------------------------",
		"| rb | SUN rasterfile format (8-bit standard)                  |",
		"| rf | GEODAS grid format GRD98 (NGDC)                         |",
		"| sf | Golden Software Surfer format 6 (float)                 |",
		"| sd | Golden Software Surfer format 7 (double, read-only)     |",
		"| af | Atlantic Geoscience Center format AGC (float)           |",
		"| gd | Import through GDAL (convert to float) -- NON-STANDARD  |",
		"----------------------------------------------------------------",
		};
