.TH PSBASEMAP 1 "Feb 27 2014" "GMT 4.5.13 (SVN)" "Generic Mapping Tools"
.SH NAME
psbasemap \- To plot \fIPostScript\fP basemaps
.SH SYNOPSIS
\fBpsbasemap\fP \fB\-B\fP[\fBp\fP|\fBs\fP]\fIparameters\fP \fB\-J\fP\fIparameters\fP \fB\-R\fP\fIwest\fP/\fIeast\fP/\fIsouth\fP/\fInorth\fP[/\fIzmin\fP/\fIzmax\fP][\fBr\fP] 
[ \fB\-E\fP\fIazim\fP/\fIelev\fP[\fB+w\fP\fIlon\fP/\fIlat\fP[/\fIz\fP]][\fB+v\fP\fIx0\fP/\fIy0\fP] ] [ \fB\-G\fP\fIfill\fP ] [ \fB\-Jz\fP|\fBZ\fP\fIparameters\fP ] [ \fB\-K\fP ] 
[ \fB\-L\fP[\fBf\fP][\fBx\fP]\fIlon0\fP/\fIlat0\fP[/\fIslon\fP]/\fIslat\fP/\fIlength\fP[\fBm\fP|\fBn\fP|\fBk\fP][\fB+l\fP\fIlabel\fP][\fB+j\fP\fIjust\fP][\fB+p\fP\fIpen\fP][\fB+f\fP\fIfill\fP][\fB+u\fP] ] ] [ \fB\-O\fP ] [ \fB\-P\fP ] [ \fB\-U\fP[\fIjust\fP/\fIdx\fP/\fIdy\fP/][\fBc\fP|\fIlabel\fP] ] 
[ \fB\-T\fP[\fBf\fP|\fBm\fP][\fBx\fP]\fIlon0\fP/\fIlat0\fP/\fIsize\fP[/\fIinfo\fP][\fB:\fPw,e,s,n\fB:\fP][\fB+\fP\fIgint\fP[/\fImint\fP]] ] [ \fB\-V\fP ] [ \fB\-X\fP[\fBa\fP|\fBc\fP|\fBr\fP][\fIx-shift\fP[\fBu\fP]] ] [ \fB\-Y\fP[\fBa\fP|\fBc\fP|\fBr\fP][\fIy-shift\fP[\fBu\fP]] ] [ \fB\-Z\fP\fIzlevel\fP ] [ \fB\-c\fP\fIcopies\fP ]
.SH DESCRIPTION
\fBpsbasemap\fP creates \fIPostScript\fP code that will produce a basemap.  Several map projections
are available, and the user may specify separate tickmark intervals for boundary annotation,
ticking, and [optionally] gridlines.  A simple map scale or directional rose may also be plotted.
.TP
\fB\-B\fP
Sets map boundary annotation and tickmark intervals. The format of \fItickinfo\fP is
[\fBp\fP|\fBs\fP]\fIxinfo\fP[/\fIyinfo\fP[/\fIzinfo\fP]][\fB:.\fP"Title"\fB:\fP][\fBW\fP|\fBw\fP][\fBE\fP|\fBe\fP][\fBS\fP|\fBs\fP][\fBN\fP|\fBn\fP][\fBZ\fP|\fBz\fP[\fB+\fP]].
The leading \fBp\fP [Default] or \fBs\fP selects the primary or secondary annotation information.
Each of the \fI?info\fP segments are textstrings of the form
\fIinfo\fP[\fB:\fP"Axis label"\fB:\fP][\fB:=\fP"prefix"\fB:\fP][\fB:,\fP"unit label"\fB:\fP].
The \fIinfo\fP string is made up of one or more concatenated substrings of the form
[\fBa\fP|\fBf\fP|\fBg\fP]\fIstride\fP[+-\fIphase\fP][\fIunit\fP].
The leading \fBa\fP is used to specify the annotation and major tick spacing [Default], \fBf\fP for minor tick spacing, and
\fBg\fP for gridline spacing.
\fIstride\fP is the desired stride interval.
The optional \fIphase\fP shifts the annotation interval by that amount (positive or negative).
The optional \fIunit\fP indicates the unit of the \fIstride\fP and can be any of
\fBY\fP (year, plot with 4 digits), \fBy\fP (year, plot with 2 digits), \fBO\fP (month, plot using \fBPLOT_DATE_FORMAT\fP),
\fBo\fP (month, plot with 2 digits), \fBU\fP (ISO week, plot using \fBPLOT_DATE_FORMAT\fP), \fBu\fP (ISO week, plot using 2 digits),
\fBr\fP (Gregorian week, 7-day stride from start of week \fBTIME_WEEK_START\fP), \fBK\fP (ISO weekday, plot name of day),
\fBD\fP (date, plot using \fBPLOT_DATE_FORMAT\fP), \fBd\fP (day, plot day of month 0-31 or year 1-366, via \fBPLOT_DATE_FORMAT\fP),
\fBR\fP (day, same as \fBd\fP, aligned with \fBTIME_WEEK_START\fP), \fBH\fP (hour, plot using \fBPLOT_CLOCK_FORMAT\fP),
\fBh\fP (hour, plot with 2 digits), \fBM\fP (minute, plot using \fBPLOT_CLOCK_FORMAT\fP), \fBm\fP (minute, plot with 2 digits), 
\fBC\fP (second, plot using \fBPLOT_CLOCK_FORMAT\fP), \fBc\fP (second, plot with 2 digits).  Note for geographic axes
\fBm\fP and \fBc\fP instead mean arc minutes and arc seconds.  All entities that are language-specific are under control
by \fBTIME_LANGUAGE\fP.  To specify separate x and y ticks, separate the substrings that apply to the x and y
axes with a slash [/] (If a 3-D basemap is selected with \fB\-E\fP and \fB\-Jz\fP, a third substring pertaining
to the vertical axis may be appended.)  For linear/log/power projections (\fB\-Jx\fP|\fBX\fP): Labels
for each axis can be added by surrounding them with colons (\fB:\fP).  If the first character in the
label is a period, then the label is used as plot title; if it is a comma (\fB,\fP) then the label is
appended to each annotation; if it is an equal sign (\fB=\fP) the the prefix is prepended to each annotation (start label/prefix
with - to avoid space between annotation and item); else it is the axis label.
If the label consists of more than one word, enclose the entire label in double quotes (e.g.,
\fB:\fP"my label"\fB:\fP).
If you need to use a colon (:) as part of your label you must specify it using its octal code (\\072).
.br
By default, all 4 boundaries are plotted (referred to as \fBW, E, S, N\fP).  To change the default,
append the code for only those axes you want (e.g., \fBWS\fP for standard lower-left x- and y-axis system).
Upper case (e.g., \fBW\fP) means draw axis/tickmarks AND annotate it, whereas lower case
(e.g., \fBw\fP) will only draw axis/tickmarks.  (If a 3-D basemap is selected with \fB\-E\fP and
\fB\-Jz\fP, append \fBZ\fP or \fBz\fP to control the appearance
of the vertical axis.  Append \fB+\fP to draw the outline of the cube defined by \fB\-R\fP.  Note
that for 3-D views the title, if given, will be suppressed.)
.br
For non-geographical projections:
Give negative scale (in \fB\-Jx\fP) or axis length (in \fB\-JX\fP) to change the direction
of increasing coordinates (i.e., to make the y-axis positive down).  For log10 axes:  Annotations
can be specified in one of three ways:  (1) \fIstride\fP can be 1, 2, 3, or -\fIn\fP.  Annotations will then
occur at 1, 1\-2\-5, or 1\-2\-3\-4\-...\-9, respectively; for -\fIn\fP we annotate every \fIn\fP't magnitude.
This option can also be used for
the frame and grid intervals.  (2) An \fBl\fP is appended to the \fItickinfo\fP string.
Then, log10 of the tick value is plotted at every integer log10 value.  (3) A \fBp\fP is appended
to the \fItickinfo\fP string.  Then, annotations appear as 10 raised to log10 of the tick value.
For power axes: Annotations can be specified in one of two ways:  (1) \fIstride\fP sets the
regular annotation interval.  (2) A \fBp\fP is appended to the \fItickinfo\fP string.  Then,
the annotation interval is expected to be in transformed units, but the annotation value
will be plotted as untransformed units.  E.g., if \fIstride\fP = 1 and \fIpower\fP = 0.5 (i.e., sqrt),
then equidistant annotations labeled 1\-4\-9... will appear.
.br
These GMT parameters can affect the appearance of the map boundary: \fBANNOT_MIN_ANGLE\fP, \fBANNOT_MIN_SPACING\fP,
\fBANNOT_FONT_PRIMARY\fP, \fBANNOT_FONT_SECONDARY\fP, \fBANNOT_FONT_SIZE_PRIMARY\fP, \fBANNOT_FONT_SIZE_SECONDARY\fP,
\fBANNOT_OFFSET_PRIMARY\fP, \fBANNOT_OFFSET_SECONDARY\fP, \fBBASEMAP_AXES\fP, \fBBASEMAP_FRAME_RGB\fP, \fBBASEMAP_TYPE\fP, \fBPLOT_DEGREE_FORMAT\fP,
\fBFRAME_PEN\fP, \fBFRAME_WIDTH\fP, \fBGRID_CROSS_SIZE_PRIMARY\fP, \fBGRID_PEN_PRIMARY\fP, \fBGRID_CROSS_SIZE_SECONDARY\fP,
\fBGRID_PEN_SECONDARY\fP, \fBHEADER_FONT\fP, \fBHEADER_FONT_SIZE\fP, \fBLABEL_FONT\fP, \fBLABEL_FONT_SIZE\fP, \fBLINE_STEP\fP,
\fBOBLIQUE_ANNOTATION\fP, \fBPLOT_CLOCK_FORMAT\fP, \fBPLOT_DATE_FORMAT\fP, \fBTIME_FORMAT_PRIMARY\fP, \fBTIME_FORMAT_SECONDARY\fP,
\fBTIME_LANGUAGE\fP, \fBTIME_WEEK_START\fP, \fBTICK_LENGTH\fP, \fBTICK_PEN\fP, and \fBY_AXIS_TYPE\fP; see the
\fBgmtdefaults\fP man page for details.
.TP
\fB\-J\fP
Selects the map projection. The following character determines the projection. If the
character is upper case then the argument(s) supplied as scale(s) is interpreted to be
the map width (or axis lengths), else the scale argument(s) is the map scale (see its
definition for each projection). UNIT is cm, inch, or m, depending on the \fBMEASURE_UNIT\fP
setting in \.gmtdefaults4, but this can be overridden on the command line by appending
\fBc\fP, \fBi\fP, or \fBm\fP to the \fIscale\fP or \fIwidth\fP values.  Append \fBh\fP, \fB+\fP, or \fB-\fP
to the given \fIwidth\fP if you instead want to set map height, the maximum dimension, or
the minimum dimension, respectively [Default is \fBw\fP for width].
.br
In case the central meridian is an optional parameter and it is being omitted, then the
center of the longitude range given by the \fB\-R\fP option is used. The default standard parallel
is the equator.
.br
The ellipsoid used in the map projections is user-definable by editing the \.gmtdefaults4 file
in your home directory. 73 commonly used ellipsoids and spheroids are currently
supported, and users may also specify their own custum ellipsoid parameters [Default is WGS-84].
Several GMT parameters can affect the projection: \fBELLIPSOID\fP, \fBINTERPOLANT\fP,
\fBMAP_SCALE_FACTOR\fP, and \fBMEASURE_UNIT\fP; see the \fBgmtdefaults\fP man page for details.
.br
Choose one of the following projections (The \fBE\fP or \fBC\fP after projection names
stands for Equal-Area and Conformal, respectively):
.RS
.PP
\fBCYLINDRICAL PROJECTIONS:\fP
.TP
\fB\-Jc\fP\fIlon0/lat0/scale\fP or \fB\-JC\fP\fIlon0/lat0/width\fP (Cassini).
Give projection center \fIlon0/lat0\fP and \fIscale\fP (\fB1:\fP\fIxxxx\fP or UNIT/degree).
.TP
\fB\-Jcyl_stere\fP/[\fIlon0/\fP[\fIlat0/\fP]]\fIscale\fP or \fB\-JCyl_stere\fP/[\fIlon0/\fP[\fIlat0/\fP]]\fIwidth\fP (Cylindrical Stereographic).
Give central meridian \fIlon0\fP (optional), standard parallel \fIlat0\fP (optional), and \fIscale\fP along parallel (\fB1:\fP\fIxxxx\fP or UNIT/degree).
The standard parallel is typically one of these (but can be any value):
.RS
.RS
66.159467 - Miller's modified Gall
.br
55 - Kamenetskiy's First
.br
45 - Gall's Stereographic
.br
30 - Bolshoi Sovietskii Atlas Mira or Kamenetskiy's Second
.br
0 - Braun's Cylindrical
.RE
.RE
.TP
\fB\-Jj\fP[\fIlon0/\fP]\fIscale\fP or \fB\-JJ\fP[\fIlon0/\fP]\fIwidth\fP (Miller Cylindrical Projection).
Give the central meridian \fIlon0\fP (optional) and \fIscale\fP (\fB1:\fP\fIxxxx\fP or UNIT/degree).
.TP
\fB\-Jm\fP[\fIlon0/\fP[\fIlat0/\fP]]\fIscale\fP or \fB\-JM\fP[\fIlon0/\fP[\fIlat0/\fP]]\fIwidth\fP
Give central meridian \fIlon0\fP (optional), standard parallel \fIlat0\fP (optional), and \fIscale\fP along parallel (\fB1:\fP\fIxxxx\fP or UNIT/degree).
.TP
\fB\-Jo\fP\fIparameters\fP (Oblique Mercator \fB[C]\fP).
Typically used with \fB\-R\fP<...>\fBr\fP, otherwise region is in oblique coordinates. Specify one of:
.RS
.TP
\fB\-Jo\fP[\fBa\fP]\fIlon0/lat0/azimuth/scale\fP or \fB\-JO\fP[\fBa\fP]\fIlon0/lat0/azimuth/width\fP
Set projection center \fIlon0/lat0\fP, \fIazimuth\fP of oblique equator, and \fIscale\fP.
.TP
\fB\-Jo\fP[\fBb\fP]\fIlon0/lat0/lon1/lat1/scale\fP or \fB\-JO\fP[\fBb\fP]\fIlon0/lat0/lon1/lat1/scale\fP
Set projection center \fIlon0/lat0\fP, another point on the oblique equator \fIlon1/lat1\fP, and \fIscale\fP.
.TP
\fB\-Joc\fP\fIlon0/lat0/lonp/latp/scale\fP or \fB\-JOc\fP\fIlon0/lat0/lonp/latp/scale\fP
Set projection center \fIlon0/lat0\fP, pole of oblique projection \fIlonp/latp\fP, and \fIscale\fP.
.PP
Give \fIscale\fP along oblique equator (\fB1:\fP\fIxxxx\fP or UNIT/degree).
.RE
.TP
\fB\-Jq\fP[\fIlon0/\fP[\fIlat0/\fP]]\fIscale\fP or \fB\-JQ\fP[\fIlon0/\fP[\fIlat0/\fP]]\fIwidth\fP (Cylindrical Equidistant).
Give the central meridian \fIlon0\fP (optional), standard parallel \fIlat0\fP (optional), and \fIscale\fP (\fB1:\fP\fIxxxx\fP or UNIT/degree).
The standard parallel is typically one of these (but can be any value):
.RS
.RS
61.7 - Grafarend and Niermann, minimum linear distortion
.br
50.5 - Ronald Miller Equirectangular
.br
43.5 - Ronald Miller, minimum continental distortion
.br
42 - Grafarend and Niermann
.br
37.5 - Ronald Miller, minimum overall distortion
.br
0 - Plate Carree, Simple Cylindrical, Plain/Plane Chart
.br
.RE
.RE
.TP
\fB\-Jt\fP\fIlon0/\fP[\fIlat0/\fP]\fIscale\fP or \fB\-JT\fP\fIlon0/\fP[\fIlat0/\fP]\fIwidth\fP
Give the central meridian \fIlon0\fP, central parallel \fIlat0\fP (optional), and \fIscale\fP (\fB1:\fP\fIxxxx\fP or UNIT/degree).
.TP
\fB\-Ju\fP\fIzone/scale\fP or \fB\-JU\fP\fIzone/width\fP (UTM - Universal Transverse Mercator \fB[C]\fP).
Give the UTM zone (A,B,1-60[C-X],Y,Z)) and \fIscale\fP (\fB1:\fP\fIxxxx\fP or UNIT/degree).
.br
Zones: If C-X not given, prepend - or + to enforce southern or northern hemisphere conventions [northern if south > 0].
.TP
\fB\-Jy\fP[\fIlon0/\fP[\fIlat0/\fP]]\fIscale\fP or \fB\-JY\fP[\fIlon0/\fP[\fIlat0/\fP]]\fIwidth\fP (Cylindrical Equal-Area \fB[E]\fP).
Give the central meridian \fIlon0\fP (optional), standard parallel \fIlat0\fP (optional), and \fIscale\fP (\fB1:\fP\fIxxxx\fP or UNIT/degree).
The standard parallel is typically one of these (but can be any value):
.RS
.RS
50 - Balthasart
.br
45 - Gall-Peters
.br
37.0666 - Caster
.br
37.4 - Trystan Edwards
.br
37.5 - Hobo-Dyer
.br
30 - Behrman
.br
0 - Lambert (default)
.RE
.RE
.PP
\fBCONIC PROJECTIONS:\fP
.TP
\fB\-Jb\fP\fIlon0/lat0/lat1/lat2/scale\fP or \fB\-JB\fP\fIlon0/lat0/lat1/lat2/width\fP (Albers \fB[E]\fP).
Give projection center \fIlon0/lat0\fP, two standard parallels \fIlat1/lat2\fP, and \fIscale\fP (\fB1:\fP\fIxxxx\fP or UNIT/degree).
.TP
\fB\-Jd\fP\fIlon0/lat0/lat1/lat2/scale\fP or \fB\-JD\fP\fIlon0/lat0/lat1/lat2/width\fP (Conic Equidistant)
Give projection center \fIlon0/lat0\fP, two standard parallels \fIlat1/lat2\fP, and \fIscale\fP (\fB1:\fP\fIxxxx\fP or UNIT/degree).
.TP
\fB\-Jl\fP\fIlon0/lat0/lat1/lat2/scale\fP or \fB\-JL\fP\fIlon0/lat0/lat1/lat2/width\fP (Lambert \fB[C]\fP)
Give origin \fIlon0/lat0\fP, two standard parallels \fIlat1/lat2\fP, and \fIscale\fP along these (\fB1:\fP\fIxxxx\fP or UNIT/degree).
.TP
\fB\-Jpoly\fP/[\fIlon0/\fP[\fIlat0/\fP]]\fIscale\fP or \fB\-JPoly\fP/[\fIlon0/\fP[\fIlat0/\fP]]\fIwidth\fP ((American) Polyconic).
Give the central meridian \fIlon0\fP (optional), reference parallel \fIlat0\fP (optional, default = equator),
and \fIscale\fP along central meridian (\fB1:\fP\fIxxxx\fP or UNIT/degree).
.PP
\fBAZIMUTHAL PROJECTIONS:\fP
.sp
Except for polar aspects, \fB\-R\fP w/e/s/n will be reset to \fB\-Rg\fP.  Use \fB\-R\fP<...>\fBr\fP for smaller regions.
.TP
\fB\-Ja\fP\fIlon0/lat0\fP[\fI/horizon\fP]\fI/scale\fP or \fB\-JA\fP\fIlon0/lat0\fP[\fI/horizon\fP]\fI/width\fP (Lambert \fB[E]\fP).
\fIlon0/lat0\fP specifies the projection center.
\fIhorizon\fP specifies the max distance from projection center (in degrees, <= 180, default 90).
Give \fIscale\fP as \fB1:\fP\fIxxxx\fP or \fIradius/lat\fP, where \fIradius\fP is distance
in UNIT from origin to the oblique latitude \fIlat\fP.
.TP
\fB\-Je\fP\fIlon0/lat0\fP[\fI/horizon\fP]\fI/scale\fP or \fB\-JE\fP\fIlon0/lat0\fP[\fI/horizon\fP]\fI/width\fP (Azimuthal Equidistant).
\fIlon0/lat0\fP specifies the projection center.
\fIhorizon\fP specifies the max distance from projection center (in degrees, <= 180, default 180).
Give \fIscale\fP as \fB1:\fP\fIxxxx\fP or \fIradius/lat\fP, where \fIradius\fP is distance
in UNIT from origin to the oblique latitude \fIlat\fP.
.TP
\fB\-Jf\fP\fIlon0/lat0\fP[\fI/horizon\fP]\fI/scale\fP or \fB\-JF\fP\fIlon0/lat0\fP[\fI/horizon\fP]\fI/width\fP (Gnomonic).
\fIlon0/lat0\fP specifies the projection center.
\fIhorizon\fP specifies the max distance from projection center (in degrees, < 90, default 60).
Give \fIscale\fP as \fB1:\fP\fIxxxx\fP or \fIradius/lat\fP, where \fIradius\fP is distance
in UNIT from origin to the oblique latitude \fIlat\fP.
.TP
\fB\-Jg\fP\fIlon0/lat0\fP[\fI/horizon\fP]\fI/scale\fP or \fB\-JG\fP\fIlon0/lat0\fP[\fI/horizon\fP]\fI/width\fP (Orthographic).
\fIlon0/lat0\fP specifies the projection center.
\fIhorizon\fP specifies the max distance from projection center (in degrees, <= 90, default 90).
Give \fIscale\fP as \fB1:\fP\fIxxxx\fP or \fIradius/lat\fP, where \fIradius\fP is distance
in UNIT from origin to the oblique latitude \fIlat\fP.
.TP
\fB\-Jg\fP\fIlon0/lat0/altitude/azimuth/tilt/twist/Width/Height/scale\fP or \fB\-JG\fP\fIlon0/lat0/altitude/azimuth/tilt/twist/Width/Height/width\fP (General Perspective).
\fIlon0/lat0\fP specifies the projection center.
\fIaltitude\fP is the height (in km) of the viewpoint above local sea level.
If \fIaltitude\fP is less than 10, then it is the distance from the center of the earth
to the viewpoint in earth radii. If \fIaltitude\fP has a suffix \fBr\fP then it is the radius
from the center of the earth in kilometers.
\fIazimuth\fP is measured to the east of north of view.
\fItilt\fP is the upward tilt of the plane of projection. If \fItilt\fP is negative, then the
viewpoint is centered on the horizon.
Further, specify the clockwise \fItwist\fP, \fIWidth\fP, and
\fIHeight\fP of the viewpoint in degrees.
Give \fIscale\fP as \fB1:\fP\fIxxxx\fP or \fIradius/lat\fP, where \fIradius\fP is distance
in UNIT from origin to the oblique latitude \fIlat\fP.
.TP
\fB\-Js\fP\fIlon0/lat0\fP[\fI/horizon\fP]\fI/scale\fP or \fB\-JS\fP\fIlon0/lat0\fP[\fI/horizon\fP]\fI/width\fP (General Stereographic \fB[C]\fP).
\fIlon0/lat0\fP specifies the projection center.
\fIhorizon\fP specifies the max distance from projection center (in degrees, < 180, default 90).
Give \fIscale\fP as \fB1:\fP\fIxxxx\fP (true at pole) or \fIlat\fP/\fB1:\fP\fIxxxx\fP (true at standard parallel \fIlat\fP)
or \fIradius/lat\fP (\fIradius\fP in UNIT from origin to the oblique latitude \fIlat\fP).
Note if \fB1:\fP\fIxxxx\fP is used then to specify \fIhorizon\fP you must also specify the \fIlat\fP as +-90 to avoid ambiguity.
.PP
\fBMISCELLANEOUS PROJECTIONS:\fP
.TP
\fB\-Jh\fP[\fIlon0/\fP]\fIscale\fP or \fB\-JH\fP[\fIlon0/\fP]\fIwidth\fP (Hammer \fB[E]\fP).
Give the central meridian \fIlon0\fP (optional) and \fIscale\fP along equator (\fB1:\fP\fIxxxx\fP or UNIT/degree).
.TP
\fB\-Ji\fP[\fIlon0/\fP]\fIscale\fP or \fB\-JI\fP[\fIlon0/\fP]\fIwidth\fP (Sinusoidal \fB[E]\fP).
Give the central meridian \fIlon0\fP (optional) and \fIscale\fP along equator (\fB1:\fP\fIxxxx\fP or UNIT/degree).
.TP
\fB\-Jkf\fP[\fIlon0/\fP]\fIscale\fP or \fB\-JKf\fP[\fIlon0/\fP]\fIwidth\fP (Eckert IV) \fB[E]\fP).
Give the central meridian \fIlon0\fP (optional) and \fIscale\fP along equator (\fB1:\fP\fIxxxx\fP or UNIT/degree).
.TP
\fB\-Jk\fP[\fBs\fP][\fIlon0/\fP]\fIscale\fP or \fB\-JK\fP[\fBs\fP][\fIlon0/\fP]\fIwidth\fP (Eckert VI) \fB[E]\fP).
Give the central meridian \fIlon0\fP (optional) and \fIscale\fP along equator (\fB1:\fP\fIxxxx\fP or UNIT/degree).
.TP
\fB\-Jn\fP[\fIlon0/\fP]\fIscale\fP or \fB\-JN\fP[\fIlon0/\fP]\fIwidth\fP (Robinson).
Give the central meridian \fIlon0\fP (optional) and \fIscale\fP along equator (\fB1:\fP\fIxxxx\fP or UNIT/degree).
.TP
\fB\-Jr\fP[\fIlon0/\fP]\fIscale\fP \fB\-JR\fP[\fIlon0/\fP]\fIwidth\fP (Winkel Tripel).
Give the central meridian \fIlon0\fP (optional) and \fIscale\fP along equator (\fB1:\fP\fIxxxx\fP or UNIT/degree).
.TP
\fB\-Jv\fP[\fIlon0/\fP]\fIscale\fP or \fB\-JV\fP[\fIlon0/\fP]\fIwidth\fP (Van der Grinten).
Give the central meridian \fIlon0\fP (optional) and \fIscale\fP along equator (\fB1:\fP\fIxxxx\fP or UNIT/degree).
.TP
\fB\-Jw\fP[\fIlon0/\fP]\fIscale\fP or \fB\-JW\fP[\fIlon0/\fP]\fIwidth\fP (Mollweide \fB[E]\fP).
Give the central meridian \fIlon0\fP (optional) and \fIscale\fP along equator (\fB1:\fP\fIxxxx\fP or UNIT/degree).
.PP
\fBNON-GEOGRAPHICAL PROJECTIONS:\fP
.TP
\fB\-Jp\fP[\fBa\fP]\fIscale\fP[\fI/origin\fP][\fBr\fP|\fBz\fP] or \fB\-JP\fP[\fBa\fP]\fIwidth\fP[\fI/origin\fP][\fBr\fP|\fBz\fP] (Polar coordinates (theta,r))
Optionally insert \fBa\fP after \fB\-Jp\fP [ or \fB\-JP\fP] for
azimuths CW from North instead of directions CCW from East [Default].
Optionally append /\fIorigin\fP in degrees to indicate an angular offset [0]).
Finally, append \fBr\fP if r is elevations in degrees (requires s >= 0 and n <= 90)
or \fBz\fP if you want to annotate depth rather than radius [Default].
Give \fIscale\fP in UNIT/r-unit.
.TP
\fB\-Jx\fP\fIx-scale\fP[\fI/y-scale\fP] or \fB\-JX\fP\fIwidth\fP[\fI/height\fP] (Linear, log, and power scaling)
Give \fIx-scale\fP (\fB1:\fP\fIxxxx\fP or UNIT/x-unit) and/or \fIy-scale\fP (\fB1:\fP\fIxxxx\fP or UNIT/y-unit); or
specify \fIwidth\fP and/or \fIheight\fP in UNIT.
\fIy-scale\fP=\fIx-scale\fP if not specified separately and using \fB1:\fP\fIxxxx\fP implies that x-unit and y-unit are in
meters.
Use negative scale(s) to reverse the direction of an axis (e.g., to have y be positive down). Set
\fIheight\fP or \fIwidth\fP to 0 to have it recomputed based on the implied scale of the other axis.
Optionally, append to \fIx-scale\fP, \fIy-scale\fP, \fIwidth\fP or \fIheight\fP one of the following:
.RS
.TP
.B d
Data are geographical coordinates (in degrees).
.TP
.B l
Take log10 of values before scaling.
.TP
\fBp\fP\fIpower\fP
Raise values to \fIpower\fP before scaling.
.TP
.B t
Input coordinates are time relative to \fBTIME_EPOCH\fP.
.TP
.B T
Input coordinates are absolute time.
.PP
Default axis lengths (see \fBgmtdefaults\fP) can be invoked
using \fB\-JXh\fP (for landscape); \fB\-JXv\fP (for portrait) will swap the x- and y-axis lengths.
The default unit for this installation is either cm or inch, as defined in the file
share/gmt_setup.conf. However, you may change this by editing your \.gmtdefaults4 file(s).
.RE
.RE
.TP
\fB\-R\fP
\fIxmin\fP, \fIxmax\fP, \fIymin\fP, and \fIymax\fP specify the Region of interest.  For geographic
regions, these limits correspond to \fIwest, east, south,\fP and \fInorth\fP and you may specify them
in decimal degrees or in [+-]dd:mm[:ss.xxx][W|E|S|N] format.  Append \fBr\fP if lower left and upper right
map coordinates are given instead of w/e/s/n.  The two shorthands \fB\-Rg\fP and \fB\-Rd\fP stand for global domain
(0/360 and -180/+180 in longitude respectively, with -90/+90 in latitude).  Alternatively, specify the name
of an existing grid file and the \fB\-R\fP settings (and grid spacing, if applicable) are copied from the grid.
For calendar time coordinates you may either give (a) relative
time (relative to the selected \fBTIME_EPOCH\fP and in the selected \fBTIME_UNIT\fP; append \fBt\fP to
\fB\-JX\fP|\fBx\fP), or (b) absolute time of the form [\fIdate\fP]\fBT\fP[\fIclock\fP]
(append \fBT\fP to \fB\-JX\fP|\fBx\fP).  At least one of \fIdate\fP and \fIclock\fP
must be present; the \fBT\fP is always required.  The \fIdate\fP string must be of the form [-]yyyy[-mm[-dd]]
(Gregorian calendar) or yyyy[-Www[-d]] (ISO week calendar), while the \fIclock\fP string must be of
the form hh:mm:ss[.xxx].  The use of delimiters and their type and positions must be exactly as indicated
(however, input, output and plot formats are customizable; see \fBgmtdefaults\fP). 
.SH OPTIONS
No space between the option flag and the associated arguments.
.TP
\fB\-E\fP
Sets the viewpoint's azimuth and elevation (for perspective view) [180/90].\"'
For frames used for animation, you may want to append \fB+\fP to fix the center
of your data domain (or specify a particular world coordinate point with \fB+w\fP\fIlon0\fP/\fIlat\fP[/\fIz\fP])
which will project to the center of your page size (or specify the coordinates
of the projected view point with \fB+v\fP\fIx0\fP/\fIy0).
.TP
\fB\-G\fP
Select fill shade, color or pattern for the inside of the basemap [Default is no fill color].
(See SPECIFYING FILL below).
.TP
\fB\-Jz\fP
Sets the vertical scaling (for 3-D maps).  Same syntax as \fB\-Jx\fP.
.TP
\fB\-K\fP
More \fIPostScript\fP code will be appended later [Default terminates the plot system].
.TP
\fB\-L\fP
Draws a simple map scale centered on \fIlon0/lat0\fP.  Use \fB\-Lx\fP to specify x/y position instead.
Scale is calculated at latitude \fIslat\fP (optionally supply longitude \fIslon\fP for oblique projections
[Default is central meridian]), \fIlength\fP is in km [miles if \fBm\fP is appended; nautical miles
if \fBn\fP is appended]. Use \fB\-Lf\fP to get a "fancy" scale [Default is plain]. Append \fB+l\fP to
select the default label which equals the distance unit (km, miles, nautical miles) and is justified on top of the scale [t].
Change this by giving your own label (append \fB+l\fP\fIlabel\fP).  Change label justification with \fB+j\fP\fIjustification\fP
(choose among l(eft), r(ight), t(op), and b(ottom)).  Apply \fB+u\fP to append the unit to all distance annotations along the scale. 
If you want to place a rectangle behind the scale, specify suitable \fB+p\fP\fIpen\fP and/or \fB+f\fP\fIfill\fP parameters.
(See SPECIFYING PENS and SPECIFYING FILL below).
.TP
\fB\-O\fP
Selects Overlay plot mode [Default initializes a new plot system].
.TP
\fB\-P\fP
Selects Portrait plotting mode [Default is Landscape, see \fBgmtdefaults\fP to change this].
.TP
\fB\-T\fP
Draws a simple map directional rose centered on \fIlon0/lat0\fP.  Use \fB\-Tx\fP to specify x/y position instead.
The \fIsize\fP is the diameter of the rose, and optional label information can be specified to override
the default values of W, E, S, and N (Give \fB::\fP to suppress all labels).  The default [plain] map rose only labels north.  Use
\fB\-Tf\fP to get a
"fancy" rose, and specify in \fIinfo\fP what you want drawn.  The default [1] draws the two principal E-W,
N-S orientations, 2 adds the two intermediate NW-SE and NE-SW orientations, while 3 adds the eight minor
orientations WNW-ESE, NNW-SSE, NNE-SSW, and ENE-WSW.  For a magnetic compass rose, specify \fB\-Tm\fP.  If given,
\fIinfo\fP must be the two parameters \fIdec/dlabel\fP, where \fIdec\fP is the magnetic declination and \fIdlabel\fP
is a label for the magnetic compass needle (specify \fB-\fP to format a label from \fIdec\fP).  Then, both directions
to geographic and magnetic north are plotted [Default is geographic only].  If the north label is \fB*\fP then a north
star is plotted instead of the north label.  Annotation and two levels of tick intervals for geographic and magnetic
directions are 10/5/1 and 30/5/1 degrees, respectively; override these settings by appending \fB+\fP\fIgints\fP[/\fImints\fP].
Color and pen attributes are taken from \fBCOLOR_BACKGROUND\fP and \fBTICK_PEN\fP, respectively, while label fonts and sizes
follow the usual annotation, label, and header font settings.
.TP
\fB\-U\fP
Draw Unix System time stamp on plot.
By adding \fIjust/dx/dy/\fP, the user may specify the justification of the stamp and
where the stamp should fall on the page relative to lower left corner of the plot.
For example, BL/0/0 will align the lower left corner of the time stamp with the lower left corner of the plot.
Optionally, append a \fIlabel\fP, or \fBc\fP (which will plot the command string.).
The \fBGMT\fP parameters \fBUNIX_TIME\fP, \fBUNIX_TIME_POS\fP, and \fBUNIX_TIME_FORMAT\fP can affect the appearance;
see the \fBgmtdefaults\fP man page for details.
The time string will be in the locale set by the environment variable \fBTZ\fP (generally local time).
.TP
\fB\-V\fP
Selects verbose mode, which will send progress reports to stderr [Default runs "silently"].
.TP
\fB\-X\fP \fB\-Y\fP
Shift plot origin relative to the current origin by (\fIx-shift,y-shift\fP) and
optionally append the length unit (\fBc\fP, \fBi\fP, \fBm\fP, \fBp\fP).
You can prepend \fBa\fP to shift the origin back to the original position after plotting,
or prepend  \fBr\fP [Default] to reset the current origin to the new location.
If \fB\-O\fP is used then the default (\fIx-shift,y-shift\fP) is (0,0), otherwise it is
(r1i, r1i) or (r2.5c, r2.5c).
Alternatively, give \fBc\fP to align the center coordinate (x or y) of the plot with the center of the page
based on current page size.
.TP
\fB\-Z\fP
For 3-D projections:  Sets the z-level of the basemap [Default is at the bottom end of the z-axis].
.TP
\fB\-c\fP
Specifies the number of plot copies. [Default is 1].
.SS SPECIFYING PENS
.TP
\fIpen\fP
The attributes of lines and symbol outlines as defined by \fIpen\fP is a comma delimetered list of
\fIwidth\fP, \fIcolor\fP and \fItexture\fP, each of which is optional.
\fIwidth\fP can be indicated as a measure (points, centimeters, inches) or as \fBfaint\fP, \fBthin\fP[\fBner\fP|\fBnest\fP],
\fBthick\fP[\fBer\fP|\fBest\fP], \fBfat\fP[\fBter\fP|\fBtest\fP], or \fBobese\fP.
\fIcolor\fP specifies a gray shade or color (see SPECIFYING COLOR below).
\fItexture\fP is a combination of dashes `-' and dots `.'.
.SS SPECIFYING FILL
.TP
\fIfill\fP
The attribute \fIfill\fP specifies the solid shade or solid \fIcolor\fP
(see SPECIFYING COLOR below) or the pattern used for filling polygons.
Patterns are specified as \fBp\fP\fIdpi/pattern\fP, where \fIpattern\fP gives
the number of the built-in pattern (1-90) \fIor\fP the name of a Sun 1-, 8-,
or 24-bit raster file. The \fIdpi\fP sets the resolution of the image. For
1-bit rasters: use \fBP\fP\fIdpi/pattern\fP for inverse video, or append
\fB:F\fP\fIcolor\fP[\fBB\fP[\fIcolor\fP]] to specify fore- and background
colors (use \fIcolor\fP = - for transparency).
See \fBGMT\fP Cookbook & Technical Reference Appendix E for information
on individual patterns.
.SS SPECIFYING COLOR
.TP
\fIcolor\fP
The \fIcolor\fP of lines, areas and patterns can be specified by a valid color name;
by a gray shade (in the range 0\-255); by a decimal color code (r/g/b, each in range 0\-255; h-s-v, ranges
0\-360, 0\-1, 0\-1; or c/m/y/k, each in range 0\-1); or by a hexadecimal color code (#rrggbb, as used in HTML).
See the \fBgmtcolors\fP manpage for more information and a full list of color names.
.SH EXAMPLES
The following section illustrates the use of the options by giving some examples for the
available map projections.  Note how scales may be given in several different ways
depending on the projection.  Also note the use of upper case letters to specify map width
instead of map scale.
.SH NON-GEOGRAPHICAL PROJECTIONS
.SS Linear x-y plot
To make a linear x/y frame with all axes, but with only left and bottom axes annotated, using xscale = yscale = 1.0,
ticking every 1 unit and annotating every 2, and using xlabel = "Distance" and ylabel = "No of samples", use
.br
.sp
\fBpsbasemap\fP \fB\-R\fP 0/9/0/5 \fB\-Jx\fP 1 \fB\-Bf\fP 1\fBa\fP2\fB:\fPDistance\fB:\fP/\fB:\fP"No of samples"\fB:\fP\fBWeSn\fP > linear.ps
.SS Log-log plot
To make a log-log frame with only the left and bottom axes, where the x-axis is 25 cm and annotated
every 1-2-5 and the y-axis is 15 cm and annotated every power of 10 but has tickmarks every 0.1, run
.br
.sp
\fBpsbasemap\fP \fB\-R\fP 1/10000/1e20/1e25 \fB\-JX\fP 25\fBcl\fP/15\fBcl\fP \fB\-B\fP 2\fB:\fPWavelength\fB:\fP/\fBa\fP1\fBpf\fP3\fB:\fPPower\fB:\fP\fBWS\fP > loglog.ps
.SS Power axes
To design an axis system to be used for a depth\-sqrt(age) plot with depth positive down, ticked and
annotated every 500m, and ages annotated at 1 my, 4 my, 9 my etc, use
.br
.sp
\fBpsbasemap\fP \fB\-R\fP 0/100/0/5000 \fB\-Jx\fP 1\fBp\fP0.5/-0.001 \fB\-B\fP 1\fBp\fP\fB:\fP"Crustal age"\fB:\fP/500\fB:\fPDepth\fB:\fP > power.ps
.SS Polar (theta,r) plot
For a base map for use with polar coordinates, where the radius from 0 to 1000 should correspond
to 3 inch and with gridlines and ticks every 30 degrees and 100 units, use
.br
.sp
\fBpsbasemap\fP \fB\-R\fP 0/360/0/1000 \fB\-JP\fP 6\fBi\fP \fB\-B\fP 30\fBp\fP/100 > polar.ps
.SH CYLINDRICAL MAP PROJECTIONS
.SS Cassini
A 10 -cm-wide basemap using the Cassini projection may be obtained by
.br
.sp
\fBpsbasemap\fP \fB\-R\fP 20/50/20/35 \fB\-JC\fP 35/28/10\fBc\fP \fB\-P\fP \fB\-B\fP 5\fBg\fP5\fB:.\fPCassini\fB:\fP > cassini.ps
.SS Mercator [conformal]
A Mercator map with scale 0.025 inch/degree along equator, and showing the length of 5000 km along the equator
(centered on 1/1 inch), may be plotted as
.br
.sp
\fBpsbasemap\fP \fB\-R\fP 90/180/-50/50 \fB\-Jm\fP 0.025\fBi\fP \fB\-B\fP 30\fBg\fP30\fB:.\fPMercator\fB:\fP \fB\-Lx\fP 1\fBi\fP/1\fBi\fP/0/5000 > mercator.ps
.SS Miller
A global Miller cylindrical map with scale 1:200,000,000 may be plotted as
.br
.sp
\fBpsbasemap\fP \fB\-Rg\fP \fB\-Jj\fP 180/1:200000000 \fB\-B\fP 30\fBg\fP30\fB:.\fPMiller\fB:\fP > miller.ps
.SS Oblique Mercator [conformal]
To create a page-size global oblique Mercator basemap for a pole at (90,30) with gridlines every 30 degrees, run
.br
.sp
\fBpsbasemap\fP  \fB\-R\fP 0/360/-70/70 \fB\-Joc\fP 0/0/90/30/0.064\fBc\fPd \fB\-B\fP 30\fBg\fP30\fB:.\fP"Oblique Mercator"\fB:\fP > oblmerc.ps
.SS Transverse Mercator [conformal]
A regular Transverse Mercator basemap for some region may look like
.br
.sp
\fBpsbasemap\fP \fB\-R\fP 69:30/71:45/-17/-15:15 \fB\-Jt\fP 70/1:1000000 \fB\-B\fP 15\fBm\fP\fB:.\fP"Survey area"\fB:\fP \fB\-P\fP > transmerc.ps
.SS Equidistant Cylindrical Projection
This projection only needs the central meridian and scale.  A 25 cm wide global basemap centered on the 130E
meridian is made by
.br
.sp
\fBpsbasemap\fP \fB\-R\fP-50/310/-90/90 \fB\-JQ\fP 130/25\fBc\fP \fB\-B\fP 30\fBg\fP30\fB:.\fP"Equidistant Cylindrical"\fB:\fP > cyl_eqdist.ps
.SS Universal Transverse Mercator [conformal]
To use this projection you must know the UTM zone number, which defines the central meridian.  A UTM
basemap for Indo-China can be plotted as
.br
.sp
\fBpsbasemap\fP \fB\-R\fP 95/5/108/20\fBr \-Ju\fP46/1:10000000 \fB\-B\fP 3\fBg\fP3\fB:.\fPUTM\fB:\fP > utm.ps
.SS Cylindrical Equal-Area
First select which of the cylindrical equal-area projections you want by deciding on the standard parallel.
Here we will use 45 degrees which gives the Gall-Peters projection.  A 9 inch wide global basemap centered on the Pacific
is made by
.br
.sp
\fBpsbasemap\fP \fB\-Rg\fP \fB\-JY\fP 180/45/9\fBi\fP \fB\-B\fP 30\fBg\fP30\fB:.\fPGall-Peters\fB:\fP > gall-peters.ps
.SH CONIC MAP PROJECTIONS
.SS Albers [equal-area]
A basemap for middle Europe may be created by
.br
.sp
\fBpsbasemap\fP \fB\-R\fP 0/90/25/55 \fB\-Jb\fP 45/20/32/45/0.25\fBc\fP \fB\-B\fP 10\fBg\fP10\fB:.\fP"Albers Equal-area"\fB:\fP > albers.ps
.SS Lambert [conformal]
Another basemap for middle Europe may be created by
.br
.sp
\fBpsbasemap\fP \fB\-R\fP 0/90/25/55 \fB\-Jl\fP 45/20/32/45/0.1\fBi\fP \fB\-B\fP 10\fBg\fP10\fB:.\fP"Lambert Conformal Conic"\fB:\fP > lambertc.ps
.SS Equidistant
Yet another basemap of width 6 inch for middle Europe may be created by
.br
.sp
\fBpsbasemap\fP \fB\-R\fP 0/90/25/55 \fB\-JD\fP 45/20/32/45/6\fBi\fP \fB\-B\fP 10\fBg\fP10\fB:.\fP"Equidistant conic"\fB:\fP > econic.ps
.SS Polyconic
A basemap for north America may be created by
.br
.sp
\fBpsbasemap\fP \fB\-R\fP-180/-20/0/90 \fB\-JPoly\fP/4\fBi\fP \fB\-B\fP 30\fBg\fP10/10\fBg\fP10\fB:.\fP"Polyconic"\fB:\fP > polyconic.ps
.SH AZIMUTHAL MAP PROJECTIONS
.SS Lambert [equal-area]
A 15 -cm-wide global view of the world from the vantage point -80/-30 will give the following basemap:
.br
.sp
\fBpsbasemap\fP \fB\-Rg\fP \fB\-JA\fP-80/-30/15\fBc\fP \fB\-B\fP 30\fBg\fP30/15\fBg\fP15\fB:.\fP"Lambert Azimuthal"\fB:\fP > lamberta.ps
.br
.sp
Follow the instructions for stereographic projection if you want to impose rectangular
boundaries on the azimuthal equal-area map but substitute \fB\-Ja\fP for \fB\-Js\fP.
.SS Equidistant
A 15 -cm-wide global map in which distances from the center (here 125/10) to any point is true can be obtained by:
.br
.sp
\fBpsbasemap\fP \fB\-Rg\fP \fB\-JE\fP 125/10/15\fBc\fP \fB\-B\fP 30\fBg\fP30/15\fBg\fP15\fB:.\fPEquidistant\fB:\fP > equi.ps
.SS Gnomonic
A view of the world from the vantage point -100/40 out to a horizon of 60 degrees from the center can be made using
the Gnomonic projection:
.br
.sp
\fBpsbasemap\fP \fB\-Rg\fP \fB\-JF\fP-100/40/60/6\fBi\fP \fB\-B\fP 30\fBg\fP30/15\fBg\fP15\fB:.\fPGnomonic\fB:\fP > gnomonic.ps
.SS Orthographic
A global perspective (from infinite distance) view of the world from the vantage point 125/10 will give
the following 6 -inch-wide basemap:
.br
.sp
\fBpsbasemap\fP \fB\-Rg\fP \fB\-JG\fP 125/10/6\fBi\fP \fB\-B\fP 30\fBg\fP30/15\fBg\fP15\fB:.\fPOrthographic\fB:\fP > ortho.ps
.SS General Perspective
The \fB\-JG\fP option can be used in a more generalized form, specifying altitude above the surface,
width and height of the view point, and twist and tilt.
A view from 160 km above -74/41.5 with a tilt of 55 and azimuth of 210 degrees, and limiting the
viewpoint to 30 degrees width and height will product a 6 -inch-wide basemap:
.br
.sp
\fBpsbasemap\fP \fB\-Rg\fP \fB\-JG\fP-74/41.5/160/210/55/30/30/6\fBi\fP \fB\-B\fP 5\fBg\fP1/5\fBg\fP1\fB:.\fP"General Perspective"\fB:\fP > genper.ps
.SS Stereographic [conformal]
To make a polar stereographic projection basemap with radius = 12 cm to \-60 degree latitude, with plot title
"Salinity measurements", using 5 degrees annotation/tick interval and 1 degree gridlines, run
.br
.sp
\fBpsbasemap\fP \fB\-R\fP-45/45/-90/-60 \fB\-Js\fP 0/-90/12\fBc\fP/-60 \fB\-B\fP 5\fBg\fP5\fB:.\fP"Salinity measurements"\fB:\fP > stereo1.ps
.br
.sp
To make a 12 -cm-wide stereographic basemap for Australia from an arbitrary view point (not the poles), and use a
rectangular boundary, we must give the pole for the new projection and use the \fB\-R\fP option to
indicate the lower left and upper right corners (in lon/lat) that will define our rectangle.  We
choose a pole at 130/-30 and use 100/-45 and 160/-5 as our corners.  The command becomes
.br
.sp
\fBpsbasemap\fP \fB\-R\fP 100/-45/160/-5\fBfP \fB\-JS\fP 130/-30/12\fBc\fP \fB\-B\fP 30\fBg\fP30/15\fBg\fP15\fB:.\fP"General Stereographic View"\fB:\fP > stereo2.ps
.SH MISCELLANEOUS MAP PROJECTIONS
.SS Hammer [equal-area]
The Hammer projection is mostly used for global maps and thus the spherical form is used.
To get a world map centered on Greenwich at a scale of 1:200000000, use
.br
.sp
\fBpsbasemap\fP \fB\-Rd\fP \fB\-Jh\fP 0/1:200000000 \fB\-B\fP 30\fBg\fP30/15\fBg\fP15\fB:.\fPHammer\fB:\fP > hammer.ps
.SS Sinusoidal [equal-area]
To make a sinusoidal world map centered on Greenwich, with a scale along the equator of 0.02 inch/degree, use
.br
.sp
\fBpsbasemap\fP \fB\-Rd\fP \fB\-Ji\fP 0/0.02\fBi\fP \fB\-B\fP 30\fBg\fP30/15\fBg\fP15\fB:.\fPSinusoidal\fB:\fP > sinus1.ps
.br
.sp
To make an interrupted sinusoidal world map with breaks at 160W, 20W, and 60E, with a scale along the equator of 0.02 inch/degree, run the following sequence of commands:
.br
.sp
\fBpsbasemap\fP \fB\-R\fP-160/-20/-90/90 \fB\-Ji\fP-90/0.02\fBi\fP \fB\-B\fP 30\fBg\fP30/15\fBg\fP15\fBWesn\fP \fB\-K\fP > sinus_i.ps
.br
\fBpsbasemap\fP \fB\-R\fP-20/60/-90/90 \fB\-Ji\fP 20/0.02\fBi\fP \fB\-B\fP 30\fBg\fP30/15\fBg\fP15\fBwesn\fP \fB\-O\fP \fB\-K\fP \fB\-X\fP 2.8\fBi\fP >> sinus_i.ps
.br
\fBpsbasemap\fP \fB\-R\fP 60/200/-90/90 \fB\-Ji\fP 130/0.02\fBi\fP \fB\-B\fP 30\fBg\fP30/15\fBg\fP15\fBwEsn\fP \fB\-O\fP \fB\-X\fP 1.6\fBi\fP >> sinus_i.ps
.br
.SS Eckert IV [equal-area]
Pseudo-cylindrical projection typically used for global maps only.  Set the central longitude and scale, e.g.,
.br
.sp
\fBpsbasemap\fP \fB\-Rg\fP \fB\-Jkf\fP 180/0.064\fBc\fP \fB\-B\fP 30\fBg\fP30/15\fBg\fP15\fB:.\fP"Eckert IV"\fB:\fP > eckert4.ps
.SS Eckert VI [equal-area]
Another pseudo-cylindrical projection typically used for global maps only.  Set the central longitude and scale, e.g.,
.br
.sp
\fBpsbasemap\fP \fB\-Rg\fP \fB\-Jks\fP 180/0.064\fBc\fP \fB\-B\fP 30\fBg\fP30/15\fBg\fP15\fB:.\fP"Eckert VI"\fB:\fP > eckert6.ps
.SS Robinson
Projection designed to make global maps "look right".  Set the central longitude and width, e.g.,
.br
.sp
\fBpsbasemap\fP \fB\-Rd\fP \fB\-JN\fP 0/8\fBi\fP \fB\-B\fP 30\fBg\fP30/15\fBg\fP15\fB:.\fPRobinson\fB:\fP > robinson.ps
.SS Winkel Tripel
Yet another projection typically used for global maps only.  You can set the central longitude, e.g.,
.br
.sp
\fBpsbasemap\fP \fB\-R\fP 90/450/-90/90 \fB\-JR\fP 270/25\fBc\fP \fB\-B\fP 30\fBg\fP30/15\fBg\fP15\fB:.\fP"Winkel Tripel"\fB:\fP > winkel.ps
.SS Mollweide [equal-area]
The Mollweide projection is also mostly used for global maps and thus the spherical form is used.
To get a 25 -cm-wide world map centered on the Dateline:
.br
.sp
\fBpsbasemap\fP \fB\-Rg\fP \fB\-JW\fP 180/25\fBc\fP \fB\-B\fP 30\fBg\fP30/15\fBg\fP15\fB:.\fPMollweide\fB:\fP > mollweide.ps
.SS Van der Grinten
The Van der Grinten projection is also mostly used for global maps and thus the spherical form is used.
To get a 7 -inch-wide world map centered on the Dateline:
.br
.sp
\fBpsbasemap\fP \fB\-Rg\fP \fB\-JV\fP 180/7\fBi\fP \fB\-B\fP 30\fBg\fP30/15\fBg\fP15\fB:.\fP"Van der Grinten"\fB:\fP > grinten.ps
.SH RESTRICTIONS
For some projections, a spherical earth is implicitly assumed.  A warning will notify the user if \fB\-V\fP
is set. Also note that plot titles are not plotted if \fB\-E\fP is given.
.SH BUGS
The \fB\-B\fP option is somewhat complicated to explain and comprehend.  However, it is fairly simple for
most applications (see examples).
.SH "SEE ALSO"
.IR gmtcolors (5),
.IR gmtdefaults (1),
.IR GMT (1)
