.TH PSLEGEND 1 "1 Jan 2013" "GMT 4.5.9" "Generic Mapping Tools"
.SH NAME
pslegend \- To plot a map legend
.SH SYNOPSIS
\fBpslegend\fP \fItextfile\fP \fB\-D\fP[\fBx\fP]\fIlon\fP/\fIlat\fP/\fIwidth\fP/\fIheight\fP/\fIjust\fP \fB\-J\fP\fIparameters\fP 
\fB\-R\fP\fIwest\fP/\fIeast\fP/\fIsouth\fP/\fInorth\fP[\fBr\fP] [ \fB\-B\fP[\fBp\fP|\fBs\fP]\fIparameters\fP ] [ \fB\-C\fP\fIdx\fP/\fIdy\fP ] [ \fB\-F\fP ] 
[ \fB\-G\fP\fIfill\fP ] [ \fB\-K\fP ] [ \fB\-L\fP\fIspacing\fP ] [ \fB\-O\fP ] [ \fB\-P\fP ] 
[ \fB\-S\fP[\fIscript\fP] ] [ \fB\-U\fP[\fIjust\fP/\fIdx\fP/\fIdy\fP/][\fBc\fP|\fIlabel\fP] ] [ \fB\-V\fP ] [ \fB\-X\fP[\fBa\fP|\fBc\fP|\fBr\fP][\fIx-shift\fP[\fBu\fP]] ] [ \fB\-c\fP\fIcopies\fP ]
[ \fB\-Y\fP[\fBa\fP|\fBc\fP|\fBr\fP][\fIy-shift\fP[\fBu\fP]] ]
.SH DESCRIPTION
\fBpslegend\fP will make legends that can be overlaid on maps.  It reads specific
legend-related information from an input file [or stdin].  Because all the elements
of the legend can already be created with other tools (\fBpsxy\fP, \fBpstext\fP) we
use those tools by creating a batch job of commands that are executed to make the final
\fIPostScript\fP overlay.  Because of this process, the option exists to just output the script which
can then be fine-tuned manually.  Unless otherwise noted, annotations will be made using the
annotation font and size in effect.
.TP
\fItextfile\fP
This file contains instruction for the layout of items in the legend.  Each legend item is described by
a unique record.  All records begin with a unique character that is common to all records of the same
kind.  The order of the legend items is implied by the order of the records.  Ten different record types
are recognized, and the syntax for each of these records are presented below:
.sp
.RS
\fB#\fP \fIcomment\fP
Records starting with # and blank lines are skipped.
.TP
\fBB\fP \fIcptname offset height\fP [ \fIoptional arguments\fP ]
The \fBB\fP record will plot a horizontal color bar, \fBpsscale\fP-style in the middle, starting at \fIoffset\fP from
the left edge, and of the given \fIheight\fP.  You may add any additional \fPpsscale\fP options from the list:
\fB\-A\fP \fB\-B\fP \fB\-E\fP \fB\-I\fP \fB\-L\fP \fB\-M\fP \fB\-N\fP \fB\-S\fP and \fB\-Z\fP.
.TP
\fBC\fP \fItextcolor\fP
The \fBC\fP record specifies the color with which the remaining text is to be printed.
\fItextcolor\fP can be in the form \fIr/g/b\fP, \fIc/m/y/k\fP, or a named color.
.TP
\fBD\fP \fIoffset pen\fP
The \fBD\fP record results in a horizontal line with specified \fIpen\fP across the legend with one quarter of
the line spacing left blank above and below the line.  Two gaps of \fIoffset\fP units are left blank between
the horizontal line and the left and right frame sides.
(See SPECIFYING PENS below).
.TP
\fBG\fP \fIgap\fP
The \fBG\fP record specifies a vertical gap of the given length. 
In addition to the standard units (\fBi\fP, \fBc\fP, \fBp\fP) you may use \fBl\fP for lines.
.TP
\fBH\fP \fIfontsize\fP|\fB-\fP \fIfont\fP|\fB-\fP header\fP
The \fBH\fP record plots a centered text string using the specified font parameters.
Use \fB-\fP to default to \fBHEADER_FONT_SIZE\fP and \fBHEADER_FONT\fP.
.TP
\fBI\fP \fIimagefile width justification\fP
Place an EPS or Sun raster image in the legend justified relative to the current point.  The
image \fIwidth\fP determines the size of the image on the page.
.TP
\fBL\fP \fIfontsize\fP|\fB-\fP \fIfont\fP|\fB-\fP justification label\fP
The \fBL\fP record plots a (L)eft, (C)entered, or (R)ight-justified text string within a column using
the specified font parameters.
Use \fB-\fP to default to \fBLABEL_FONT_SIZE\fP and \fBLABEL_FONT\fP.
.TP
\fBM\fP \fIslon\fP|\fB-\fP \fIslat length\fP \fBf\fP|\fBp\fP [ \fB\-R\fP\fIw/e/s/n\fP \fB\-J\fP\fIparam\fP ]
Place a map scale in the legend.  Specify \fIslon slat\fP, the point on the map where the scale applies (\fIslon\fP
is only meaningful for certain oblique projections.  If not needed, you must specify \fB-\fP instead),
\fIlength\fP, the length of the scale in km (append \fBm\fP or \fBn\fP for miles or nautical miles), and
\fBf\fP or \fBp\fP for fancy or plain scale.  If the \fB\-R\fP \fB\-J\fP supplied to \fBpslegend\fP is different than the
projection needed for the scale, supply the optional \fB\-R\fP \fB\-J\fP settings as well.  
Append \fB+l\fP to the \fIlength\fP to
select the default label which equals the distance unit (km, miles, nautical miles) and is justified on top of the scale [t].
Change this by giving your own label (append \fB+l\fP\fIlabel\fP).  Change label justification with \fB+j\fP\fIjustification\fP
(choose among l(eft), r(ight), t(op), and b(ottom)).  Apply \fB+u\fP to append the unit to all distance annotations along the scale. 
If you want to place a rectangle behind the scale, specify suitable \fB+p\fP\fIpen\fP and/or \fB+f\fP\fIfill\fP parameters.
All these \fP+\fP\fImodifiers\fP are appended to \fIlength\fP to make a single string.
(See SPECIFYING PENS and SPECIFYING FILL below).
.TP
\fBN\fP \fIncolumns\fP
Change the number of columns in the legend [1]. This only affects the printing of symbols (\fBS\fP) and 
labels (\fBL\fP).
.TP
\fBS\fP \fIdx1 symbol size fill pen\fP [ \fIdx2 text\fP ]
Plots the selected symbol with specified size, fill, and outline (see \fBpsxy\fP).
The symbol is centered at \fIdx1\fP from the left margin of the column,
with the optional explanatory \fItext\fP starting \fIdx2\fP from the margin, printed with fontsize
\fBANNOT_FONT_SIZE_PRIMARY\fP and font \fBANNOT_FONT_PRIMARY\fP.
Use \fB-\fP if no \fIfill\fP or outline (\fIpen\fP) is required.
When plotting just a symbol, without text, \fIdx2\fP and \fItext\fP can be omitted.
Two \fBpsxy\fP symbols require special attention: front (f) and vector (v).  You must prepend
the length of the desired item to the rest of the symbol argument; this will be used internally to set the
correct fault or vector length and will be stripped before passing the arguments to \fBpsxy\fP.
.TP
\fBT\fP \fIparagraph-text\fP
One or more of these \fBT\fP records with \fIparagraph-text\fP printed with fontsize
\fBANNOT_FONT_SIZE_PRIMARY\fP and font \fBANNOT_FONT_PRIMARY\fP (aligned and wrapped).
To specify special positioning and typesetting arrangements, or to enter a paragraph break, use the
optional \fB>\fP record.
.TP
\fBV\fP \fIoffset pen\fP
The \fBV\fP record draws a vertical line between columns (if more than one) using the selected \fIpen\fP
(See SPECIFYING PENS below).
\fIoffset\fP is analogous to the offset for the \fBD\fP records but in the vertical direction.
.TP
\fB>\fP \fIparagraph-mode-header-for-pstext\fP
Start a new text paragraph by specifying all the parameters needed (see \fBpstext \-m\fP description).  Note that
\fBpslegend\fP knows what all those values should be, so normally you can leave the entire record (after >) blank or
leave it out all together.
If you need to set at least one of the parameters directly, you must specify all and set the ones you want to leave
at their default value to \fB-\fP.
.RE
.br
.TP
\fB\-D\fP
Positions the legend and specifies its size.  The \fIjust\fP is a 2-char justification string (see \fBpstext\fP)
that relates the given position to a point on the rectangular legend box.  If you want to specify the position
in map plot units (i.e., inches or cm), use \fB\-Dx\fP.
.TP
\fB\-J\fP
Selects the map projection. Scale is UNIT/degree, 1:xxxxx, or width in UNIT (upper case modifier).
UNIT is cm, inch, or m, depending on the \fBMEASURE_UNIT\fP setting in \.gmtdefaults4, but this can be
overridden on the command line by appending \fBc\fP, \fBi\fP, or \fBm\fP to the scale/width value.
When central meridian is optional, default is center of longitude range on \fB\-R\fP option.
Default standard parallel is the equator.
For map height, max dimension, or min dimension, append \fBh\fP, \fB+\fP, or \fB-\fP to the width,
respectively.
.br
More details can be found in the \fBpsbasemap\fP man pages.
.br
.sp
\fBCYLINDRICAL PROJECTIONS:\fP
.br
.sp
\fB\-Jc\fP\fIlon0/lat0/scale\fP (Cassini)
.br
\fB\-Jcyl_stere\fP/[\fIlon0/\fP[\fIlat0/\fP]]\fIscale\fP (Cylindrical Stereographic)
.br
\fB\-Jj\fP[\fIlon0/\fP]\fIscale\fP (Miller)
.br
\fB\-Jm\fP[\fIlon0\fP/[\fIlat0/\fP]]\fIscale\fP (Mercator)
.br
\fB\-Jm\fP\fIlon0/lat0/scale\fP (Mercator - Give meridian and standard parallel)
.br
\fB\-Jo\fP[\fBa\fP]\fIlon0/lat0/azimuth/scale\fP (Oblique Mercator - point and azimuth)
.br
\fB\-Jo\fP[\fBb\fP]\fIlon0/lat0/lon1/lat1/scale\fP (Oblique Mercator - two points)
.br
\fB\-Joc\fP\fIlon0/lat0/lonp/latp/scale\fP (Oblique Mercator - point and pole)
.br
\fB\-Jq\fP[\fIlon0/\fP[\fIlat0/\fP]]\fIscale\fP (Cylindrical Equidistant)
.br
\fB\-Jt\fP\fIlon0/\fP[\fIlat0/\fP]\fIscale\fP (TM - Transverse Mercator)
.br
\fB\-Ju\fP\fIzone/scale\fP (UTM - Universal Transverse Mercator)
.br
\fB\-Jy\fP[\fIlon0/\fP[\fIlat0/\fP]]\fIscale\fP (Cylindrical Equal-Area) 
.br
.sp
\fBCONIC PROJECTIONS:\fP
.br
.sp
\fB\-Jb\fP\fIlon0/lat0/lat1/lat2/scale\fP (Albers)
.br
\fB\-Jd\fP\fIlon0/lat0/lat1/lat2/scale\fP (Conic Equidistant)
.br
\fB\-Jl\fP\fIlon0/lat0/lat1/lat2/scale\fP (Lambert Conic Conformal)
.br
\fB\-Jpoly\fP/[\fIlon0/\fP[\fIlat0/\fP]]\fIscale\fP ((American) Polyconic)
.br
.sp
\fBAZIMUTHAL PROJECTIONS:\fP
.br
.sp
\fB\-Ja\fP\fIlon0/lat0\fP[\fI/horizon\fP]\fI/scale\fP (Lambert Azimuthal Equal-Area)
.br
\fB\-Je\fP\fIlon0/lat0\fP[\fI/horizon\fP]\fI/scale\fP (Azimuthal Equidistant)
.br
\fB\-Jf\fP\fIlon0/lat0\fP[\fI/horizon\fP]\fI/scale\fP (Gnomonic)
.br
\fB\-Jg\fP\fIlon0/lat0\fP[\fI/horizon\fP]\fI/scale\fP (Orthographic)
.br
\fB\-Jg\fP\fIlon0/lat0/altitude/azimuth/tilt/twist/Width/Height/scale\fP (General Perspective).
.br
\fB\-Js\fP\fIlon0/lat0\fP[\fI/horizon\fP]\fI/scale\fP (General Stereographic)
.br
.sp
\fBMISCELLANEOUS PROJECTIONS:\fP
.br
.sp
\fB\-Jh\fP[\fIlon0/\fP]\fIscale\fP (Hammer)
.br
\fB\-Ji\fP[\fIlon0/\fP]\fIscale\fP (Sinusoidal)
.br
\fB\-Jkf\fP[\fIlon0/\fP]\fIscale\fP (Eckert IV)
.br
\fB\-Jk\fP[\fBs\fP][\fIlon0/\fP]\fIscale\fP (Eckert VI)
.br
\fB\-Jn\fP[\fIlon0/\fP]\fIscale\fP (Robinson)
.br
\fB\-Jr\fP[\fIlon0/\fP]\fIscale\fP (Winkel Tripel)
.br
\fB\-Jv\fP[\fIlon0/\fP]\fIscale\fP (Van der Grinten)
.br
\fB\-Jw\fP[\fIlon0/\fP]\fIscale\fP (Mollweide)
.br
.sp
\fBNON-GEOGRAPHICAL PROJECTIONS:\fP
.br
.sp
\fB\-Jp\fP[\fBa\fP]\fIscale\fP[\fI/origin\fP][\fBr\fP|\fBz\fP] (Polar coordinates (theta,r))
.br
\fB\-Jx\fP\fIx-scale\fP[\fBd\fP|\fBl\fP|\fBp\fP\fIpow\fP|\fBt\fP|\fBT\fP][\fI/y-scale\fP[\fBd\fP|\fBl\fP|\fBp\fP\fIpow\fP|\fBt\fP|\fBT\fP]] (Linear, log, and power scaling)
.br
.TP
\fB\-R\fP
\fIxmin\fP, \fIxmax\fP, \fIymin\fP, and \fIymax\fP specify the Region of interest.  For geographic
regions, these limits correspond to \fIwest, east, south,\fP and \fInorth\fP and you may specify them
in decimal degrees or in [+-]dd:mm[:ss.xxx][W|E|S|N] format.  Append \fBr\fP if lower left and upper right
map coordinates are given instead of w/e/s/n.  The two shorthands \fB\-Rg\fP and \fB\-Rd\fP stand for global domain
(0/360 and -180/+180 in longitude respectively, with -90/+90 in latitude).  Alternatively, specify the name
of an existing grid file and the \fB\-R\fP settings (and grid spacing, if applicable) are copied from the grid.
For calendar time coordinates you may either give (a) relative
time (relative to the selected \fBTIME_EPOCH\fP and in the selected \fBTIME_UNIT\fP; append \fBt\fP to
\fB\-JX\fP|\fBx\fP), or (b) absolute time of the form [\fIdate\fP]\fBT\fP[\fIclock\fP]
(append \fBT\fP to \fB\-JX\fP|\fBx\fP).  At least one of \fIdate\fP and \fIclock\fP
must be present; the \fBT\fP is always required.  The \fIdate\fP string must be of the form [-]yyyy[-mm[-dd]]
(Gregorian calendar) or yyyy[-Www[-d]] (ISO week calendar), while the \fIclock\fP string must be of
the form hh:mm:ss[.xxx].  The use of delimiters and their type and positions must be exactly as indicated
(however, input, output and plot formats are customizable; see \fBgmtdefaults\fP). 
.SH OPTIONS
No space between the option flag and the associated arguments.
.TP
\fB\-B\fP
Sets map boundary annotation and tickmark intervals; see the
\fBpsbasemap\fP man page for all the details.
.TP
\fB\-C\fP
Sets the clearance between the legend frame and the internal items [0.15\fBc\fP/0.15\fBc\fP (or 0.05\fBi\fP/0.05\fBi\fP)].
.TP
\fB\-F\fP
Draws a border around the legend using \fBFRAME_PEN\fP.
.TP
\fB\-G\fP
Select fill shade, color or pattern of the legend box [Default is no fill].
(See SPECIFYING FILL below).
.TP
\fB\-K\fP
More \fIPostScript\fP code will be appended later [Default terminates the plot system].
.TP
\fB\-L\fP
Sets the linespacing factor in units of the current annotation font size [1.1].
.TP
\fB\-O\fP
Selects Overlay plot mode [Default initializes a new plot system].
.TP
\fB\-P\fP
Selects Portrait plotting mode [Default is Landscape, see \fBgmtdefaults\fP to change this].
.TP
\fB\-S\fP
Instead of writing the \fIPostScript\fP plot [Default], output the \fBGMT\fP script used to make the legend
to standard output, or optionally to the file \fIscript\fP.
.TP
\fB\-U\fP
Draw Unix System time stamp on plot.
By adding \fIjust/dx/dy/\fP, the user may specify the justification of the stamp and
where the stamp should fall on the page relative to lower left corner of the plot.
For example, BL/0/0 will align the lower left corner of the time stamp with the lower left corner of the plot.
Optionally, append a \fIlabel\fP, or \fBc\fP (which will plot the command string.).
The \fBGMT\fP parameters \fBUNIX_TIME\fP, \fBUNIX_TIME_POS\fP, and \fBUNIX_TIME_FORMAT\fP can affect the appearance;
see the \fBgmtdefaults\fP man page for details.
The time string will be in the locale set by the environment variable \fBTZ\fP (generally local time).
.TP
\fB\-V\fP
Selects verbose mode, which will send progress reports to stderr [Default runs "silently"].
.TP
\fB\-X\fP \fB\-Y\fP
Shift plot origin relative to the current origin by (\fIx-shift,y-shift\fP) and
optionally append the length unit (\fBc\fP, \fBi\fP, \fBm\fP, \fBp\fP).
You can prepend \fBa\fP to shift the origin back to the original position after plotting,
or prepend  \fBr\fP [Default] to reset the current origin to the new location.
If \fB\-O\fP is used then the default (\fIx-shift,y-shift\fP) is (0,0), otherwise it is
(r1i, r1i) or (r2.5c, r2.5c).
Alternatively, give \fBc\fP to align the center coordinate (x or y) of the plot with the center of the page
based on current page size.
.TP
\fB\-c\fP
Specifies the number of plot copies. [Default is 1].
.SS SPECIFYING PENS
.TP
\fIpen\fP
The attributes of lines and symbol outlines as defined by \fIpen\fP is a comma delimetered list of
\fIwidth\fP, \fIcolor\fP and \fItexture\fP, each of which is optional.
\fIwidth\fP can be indicated as a measure (points, centimeters, inches) or as \fBfaint\fP, \fBthin\fP[\fBner\fP|\fBnest\fP],
\fBthick\fP[\fBer\fP|\fBest\fP], \fBfat\fP[\fBter\fP|\fBtest\fP], or \fBobese\fP.
\fIcolor\fP specifies a gray shade or color (see SPECIFYING COLOR below).
\fItexture\fP is a combination of dashes `-' and dots `.'.
.SS SPECIFYING FILL
.TP
\fIfill\fP
The attribute \fIfill\fP specifies the solid shade or solid \fIcolor\fP
(see SPECIFYING COLOR below) or the pattern used for filling polygons.
Patterns are specified as \fBp\fP\fIdpi/pattern\fP, where \fIpattern\fP gives
the number of the built-in pattern (1-90) \fIor\fP the name of a Sun 1-, 8-,
or 24-bit raster file. The \fIdpi\fP sets the resolution of the image. For
1-bit rasters: use \fBP\fP\fIdpi/pattern\fP for inverse video, or append
\fB:F\fP\fIcolor\fP[\fBB\fP[\fIcolor\fP]] to specify fore- and background
colors (use \fIcolor\fP = - for transparency).
See \fBGMT\fP Cookbook & Technical Reference Appendix E for information
on individual patterns.
.SS SPECIFYING COLOR
.TP
\fIcolor\fP
The \fIcolor\fP of lines, areas and patterns can be specified by a valid color name;
by a gray shade (in the range 0\-255); by a decimal color code (r/g/b, each in range 0\-255; h-s-v, ranges
0\-360, 0\-1, 0\-1; or c/m/y/k, each in range 0\-1); or by a hexadecimal color code (#rrggbb, as used in HTML).
See the \fBgmtcolors\fP manpage for more information and a full list of color names.
.SH EXAMPLES
To add an example of a legend to a Mercator plot (map.ps) with the given specifications, use
.br
.sp
\fBpslegend\fP \fB\-R\fP-10/10/-10/10 \fB\-JM\fP6i \fB\-G\fPazure1 \fB\-Dx\fP0.5i/0.5i/5i/3.3i/BL
\fB\-C\fP0.1i/0.1i \fB\-L\fP1.2 \fB\-F\fP \fB\-B\fP5f1 << EOF >> map.ps
.br
\# Legend test for pslegend
.br
\# G is vertical gap, V is vertical line, N sets # of columns, D draws horizontal line.
.br
\# H is header, L is label, S is symbol, T is paragraph text, M is map scale.
.br
\#
.br
G -0.1i
.br
H 24 Times-Roman My Map Legend
.br
D 0.2i 1p
.br
N 2
.br
V 0 1p
.br
S 0.1i c 0.15i p300/12 0.25p 0.3i This circle is hachured
.br
S 0.1i e 0.15i 255/255/0 0.25p 0.3i This ellipse is yellow
.br
S 0.1i w 0.15i 0/255/0 0.25p 0.3i This wedge is green
.br
S 0.1i f 0.25i/-1/0.075ilb 0/0/255 0.25p 0.3i This is a fault
.br
S 0.1i - 0.15i - 0.25tap 0.3i A contour
.br
S 0.1i v 0.25i/0.02i/0.06i/0.05i 255/0/255 0.25p 0.3i This is a vector
.br
S 0.1i i 0.15i 0/255/255 0.25p 0.3i This triangle is boring
.br
V 0 1p
.br
D 0.2i 1p
.br
N 1
.br
M 5 5 600+u f
.br
G 0.05i
.br
I SOEST_logo.ras 3i CT
.br
G 0.05i
.br
B colors.cpt 0.2i 0.2i
.br
G 0.05i
L 9 4 R Smith et al., @%5%J. Geophys. Res., 99@%%, 2000
.br
G 0.1i
.br
T Let us just try some simple text that can go on a few lines.
.br
T There is no easy way to predetermine how many lines will be required,
.br
T so we may have to adjust the box height to get the right size box.
.br
EOF
.br
.SH WINDOWS REMARKS
Note that under Windows, the percent sign (%) is a variable indicator (like $ under Unix).
To indicate a plain percentage sign in a batch script you need to repeat it (%%);
hence the font switching mechanism (@%\fIfont\fP% and @%%) may require twice the
number of percent signs.  This only applies to text inside a script or that otherwise
is processed by DOS.  Data files that are opened and read by \fBpslegend\fP do not need such duplication.
.SH "SEE ALSO"
.IR GMT (1),
.IR gmtcolors (5),
.IR gmtdefaults (1),
.IR psbasemap (1),
.IR pstext (1),
.IR psxy (1)
