.TH GMT2KML 1 "5 Nov 2013" "GMT 4.5.11" "Generic Mapping Tools"
.SH NAME
gmt2kml \- Convert GMT data tables to KML files for Google Earth 
.SH SYNOPSIS
\fBgmt2kml\fP [ \fIinfile(s)\fP ] [ \fB\-A\fP\fBa\fP|\fBg\fP|\fBs\fP[\fIalt\fP|\fBx\fP\fIscale\fP] ]
[ \fB\-C\fP\fIcpt\fP ]
[ \fB\-D\fP\fIdescriptfile\fP ] [ \fB\-E\fP[\fIaltitude\fP] ] [ \fB\-F\fP\fBe\fP|\fBs\fP[\fIcpt\fP]|\fBt\fP|\fBl\fP|\fBp\fP ] 
[ \fB\-G\fP\fBf|n[-|\fP\fIfill\fP] ] [ \fB\-H\fP[\fBi\fP][\fInrec\fP] ] [ \fB\-I\fP\fIicon\fP ] [ \fB\-K\fP]
[ \fB\-L\fP\fIcol1:name1,col2:name2,...\fP ] 
[ \fB\-N\fP[+|\fIname_template\fP|\fIname\fP] ] [ \fB\-O\fP] [ \fB\-Q\fP[\fBs\fP|\fBl\fP|\fBp\fP]\fItransparency\fP ] 
[ \fB\-Ra\fP|\fIw/e/s/n\fP ] 
[ \fB\-S\fP\fBc\fP|\fBn\fP\fIscale\fP] ] [ \fB\-T\fP\fItitle\fP[/\fIfoldername\fP] ] [ \fB\-V\fP ] 
[ \fB\-W\fP-|\fIpen\fP ] [ \fB\-Z\fP\fIargs\fP ] [ \fB\-:\fP[\fBi\fP|\fBo\fP] ] [ \fB\-bi\fP[\fBs\fP|\fBS\fP|\fBd\fP|\fBD\fP[\fIncol\fP]|\fBc\fP[\fIvar1\fP\fB/\fP\fI...\fP]] ] [ \fB\-f\fP[\fBi\fP|\fBo\fP]\fIcolinfo\fP ] [ \fB\-m\fP[\fBi\fP|\fBo\fP][\fIflag\fP] ] [ > \fIoutput.kml\fP ]
.SH DESCRIPTION
\fBgmt2kml\fP reads one or more GMT table file and converts them to a single output file
using Google Earth's KML format.
Data may represent points, lines, or polygons, and you may specify additional
attributes such as title, altitude mode, colors, pen widths, transparency, regions, and data descriptions.
You may also extend the feature down to ground level (assuming it is above it) and use
custom icons for point symbols.
.br
The input file should contain the following columns:
.br
\fIlon\fP \fIlat\fP [ \fIalt\fP ] [ \fItimestart\fP [ \fItimestop\fP ] ]
.br
where \fIlon\fP and \fIlat\fP are required for all features, \fIalt\fP is optional for all features (see
also \fB\-A\fP and \fB\-C\fP), and \fItimestart\fP and \fItimestop\fP apply to events and timespan features.
.TP
\fIinfile(s)\fP
ASCII (or binary, see \fB\-bi\fP) data file(s) to be operated on.  If not given, standard input will be read.
.SH OPTIONS
No space between the option flag and the associated arguments.
.TP
\fB\-A\fP
Select one of three altitude modes recognized by Google Earth that determines the altitude (in m) of the
feature:
\fBa\fP absolute altitude,
\fBg\fP altitude relative to sea surface or ground,
\fBs\fP altitude relative to seafloor.
To plot the features at a fixed altitude, append an altitude \fIalt\fP (in m). Use 0 to clamp the features to the chosen reference
surface.
Append \fBx\fP\fIscale\fP to scale the altitude from the input file by that factor.
If no value is appended, the altitude (in m) is read from the 3rd column of the input file.
[By default the features are clamped to the sea surface or ground].
.TP
\fB\-C\fP
Use color palette for assigning colors to the symbol, event, or timespan icons, based on the value in the 3rd column
of the input file. Ignored when plotting lines or polygons.
.TP
\fB\-D\fP
File with HTML snippets that will be included as part of the main description content for the KML file [no description].
See SEGMENT INFORMATION below for feature-specific descriptions.
.TP
\fB\-E\fP
Extrude feature down to ground level [no extrusion].
.TP
\fB\-F\fP
Sets the feature type.  Choose from points (\fBe\fPvent, \fBs\fPymbol, or \fBt\fPimespan), \fBl\fPine, or \fBp\fPolygon [symbol].
The first two columns of the input file should contain (\fIlon, lat\fP).
When altitude or value is required (i.e., no \fIaltitude\fP value was given with \fB\-A\fP, or \fB\-C\fP is set), the third column needs to contain
the \fIaltitude\fP (in m).
The event (\fB\-Fe\fP) is a symbol that should only be active at a particular \fItime\fP, given in the next column.
Timespan (\fB\-Ft\fP) is a symbol that should only be active during a particular time period indicated by the next
two columns (\fItimestart, timestop\fP).  Use NaN to indicate unbounded time limits.
If used, times should be in ISO format yyyy-mm-ddThh:mm:ss[.xxx] or in GMT relative time format (see \fB\-f\fP).
.TP
\fB\-G\fP
Set fill color for symbols, extrusions and polygons (\fB\-Gf\fP) [Default is lightorange] or text labels (\fB\-Gn\fP) [Default is white].
Optionally, use \fB\-Gf-\fP to turn off polygon fill, and \fB\-Gn-\fP to disable labels.
(See SPECIFYING FILL below).
.TP
\fB\-H\fP
Input file(s) has header record(s).  If used, the default number of header records is \fBN_HEADER_RECS\fP.
Use \fB\-Hi\fP if only input data should have header records [Default will write out header records if the
input data have them]. Blank lines and lines starting with # are always skipped.
.TP
\fB\-I\fP
Specify the URL to an alternative icon that should be used for the symbol [Default is a Google Earth circle].
If the URL starts with + then we will prepend http://maps.google.com/mapfiles/kml/ to the name.
[Default is a local icon with no directory path].
.TP
\fB\-K\fP
Allow more KML code to be appended to the output later [finalize the KML file].
.TP
\fB\-L\fP
Extended data given.  Append one or more strings of the form \fIcol\fP:\fIname\fP separated by commas.
We will expect the listed data columns to exist in the input and they will be encoded in the KML file as
Extended Data sets, whose attributes will be available in the Google Earth balloon when the item is selected.
.TP
\fB\-N\fP
By default, if multisegment headers contain a \fB\-L\fP"label string" then we use that for the name of
the KML feature (polygon, line segment or set of symbols). Default names for these segments are "Line %d" and
"Point Set %d", depending on the feature, where %d is a sequence number of line segments within a file.
Each point within a line segment will be named after the line segment plus a sequence number. Default is simply 
"Point %d".
.br
Alternatively, select one of these options:
(1) append \fB+\fP to supply individual symbol labels directly at the end of the data record,
(2) append a string that may include %d or a similar integer format to assign unique name IDs for each feature,
with the segment number (for lines and polygons) or point number (symbols) appearing where %d is placed,
(3) give no arguments to turn symbol labeling off; line segments will still be named.
.TP
\fB\-O\fP
Appended KML code to an existing KML file [initialize a new KML file].
.TP
\fB\-Q\fP
Set the transparency level for the selected feature (\fBe\fP, \fBs\fP, \fBt\fP, \fBl\fP, or \fBp\fP,
plus \fBn\fP for name labels).  Transparency
goes from 0 (fully transparent) to 1 (opaque) [0.75 for polygons, 1 for symbols, lines, and labels].
.TP
\fB\-R\fP
Issue a single Region tag.  Append \fIw/e/s/n\fP to set a particular region (will ignore points outside
the region), or append \fBa\fP to determine and use the actual domain of the data (single file only) [no region tags issued].
.TP
\fB\-S\fP
Scale icons or labels.  Here, \fB\-Sc\fP sets a scale for the symbol icon, whereas \fB\-Sn\fP sets a scale for the name labels [1 for both].
.TP
\fB\-T\fP
Sets the document title [GMT Data Document].  Optionally, append /\fIFolderName\fP;
this allows you, with \fB\-O\fP, \fB\-K\fP, to group features into folders within the KML document.
[The default folder name is "\fIName\fP Features", where \fIName\fP is Point, Event, Timespan, Line, or Polygon].
.TP
\fB\-V\fP
Selects verbose mode, which will send progress reports to stderr [Default runs "silently"].
.TP
\fB\-W\fP
Set pen attributes for lines or polygon outlines.  Append pen attributes to use
[Defaults: width = 1p, color = black, texture = solid].  Optionally, use \fB\-W-\fP to
turn off polygon outline  Note that for KML the pen width is given as integer pixel
widths so you must specify pen width as \fIn\fP\fBp\fP, where \fIn\fP is an integer.
(See SPECIFYING PENS below).
.TP
\fB\-Z\fP
Set one or more attributes of the Document and Region tags.
Append \fB+a\fP\fIalt_min/alt_max\fP to specify limits on visibility based on altitude.
Append \fB+l\fP\fIlod_min/lod_max\fP to specify limits on visibility based on Level Of Detail,
where \fIlod_max\fP == -1 means it is visible to infinite size.
Append \fB+f\fP\fIfade_min/fade_max\fP to fade in and out over a ramp [abrupt].
Append \fB+v\fP to make a feature \fInot\fP visible when loaded [visible].
Append \fB+o\fP to open a folder or document in the sidebar when loaded [closed].
.TP
\fB\-:\fP
Toggles between (longitude,latitude) and (latitude,longitude) input and/or output.  [Default is (longitude,latitude)].
Append \fBi\fP to select input only or \fBo\fP to select output only.  [Default affects both].
.TP
\fB\-bi\fP
Selects binary input.
Append \fBs\fP for single precision [Default is \fBd\fP (double)].
Uppercase \fBS\fP or \fBD\fP will force byte-swapping.
Optionally, append \fIncol\fP, the number of columns in your binary input file
if it exceeds the columns needed by the program.
Or append \fBc\fP if the input file is netCDF. Optionally, append \fIvar1\fP\fB/\fP\fIvar2\fP\fB/\fP\fI...\fP to
specify the variables to be read.
[Default is 2 input columns].
.TP
\fB\-f\fP
Special formatting of input and/or output columns (time or geographical data).
Specify \fBi\fP or \fBo\fP to make this apply only to input or output [Default applies to both].
Give one or more columns (or column ranges) separated by commas.
Append \fBT\fP (absolute calendar time), \fBt\fP (relative time in chosen \fBTIME_UNIT\fP since \fBTIME_EPOCH\fP),
\fBx\fP (longitude), \fBy\fP (latitude), or \fBf\fP (floating point) to each column
or column range item.  Shorthand \fB\-f\fP[\fBi\fP|\fBo\fP]\fBg\fP means \fB\-f\fP[\fBi\fP|\fBo\fP]0\fBx\fP,1\fBy\fP
(geographic coordinates).
.TP
\fB\-m\fP
Multiple segment file(s).  Segments are separated by a special record.
For ASCII files the first character must be \fIflag\fP [Default is '>'].
For binary files all fields must be NaN and \fB\-b\fP must
set the number of output columns explicitly.  By default the \fB\-m\fP
setting applies to both input and output.  Use \fB\-mi\fP and \fB\-mo\fP
to give separate settings to input and output.
The \fB\-m\fP option make sure that segment headers in the input files are copied to output, but it has no effect
on the data selection. Selection is always done point by point, not by segment.
.SS SPECIFYING PENS
.TP
\fIpen\fP
The attributes of lines and symbol outlines as defined by \fIpen\fP is a comma delimetered list of
\fIwidth\fP, \fIcolor\fP and \fItexture\fP, each of which is optional.
\fIwidth\fP can be indicated as a measure (points, centimeters, inches) or as \fBfaint\fP, \fBthin\fP[\fBner\fP|\fBnest\fP],
\fBthick\fP[\fBer\fP|\fBest\fP], \fBfat\fP[\fBter\fP|\fBtest\fP], or \fBobese\fP.
\fIcolor\fP specifies a gray shade or color (see SPECIFYING COLOR below).
\fItexture\fP is a combination of dashes `-' and dots `.'.
.SS SPECIFYING COLOR
.TP
\fIcolor\fP
The \fIcolor\fP of lines, areas and patterns can be specified by a valid color name;
by a gray shade (in the range 0\-255); by a decimal color code (r/g/b, each in range 0\-255; h-s-v, ranges
0\-360, 0\-1, 0\-1; or c/m/y/k, each in range 0\-1); or by a hexadecimal color code (#rrggbb, as used in HTML).
See the \fBgmtcolors\fP manpage for more information and a full list of color names.
.SH "EXAMPLES"
To convert a file with point locations (lon, lat) into a KML file with red circle symbols, try
.br
.sp
gmt2kml mypoints.txt \fB\-Gf\fP red \fB\-Fs\fP > mypoints.kml
.br
.sp
To convert a multisegment file with lines (lon, lat) separated by multisegment headers that contain
a \fB\-L\fP labelstring with the feature name, selecting a thick white pen, and title the document, try
.br
.sp
gmt2kml mylines.txt \fB\-W\fP thick,white \fB\-Fl\fP \fB\-T\fP"Lines from here to there" > mylines.kml
.br
.sp
To convert a multisegment file with polygons (lon, lat) separated by multisegment headers that contain
a \fB\-L\fP labelstring with the feature name, selecting a thick black pen and semi-transparent yellow fill,
giving a title to the document, and prescribing a particular region limit, try
.br
.sp
gmt2kml mypolygons.txt \fB\-Gf\fP yellow \fB\-Qp\fP 0.5 \fB\-Fp\fP \fB\-T\fP"My polygons" \fB\-R\fP 30/90/-20/40 > mypolygons.kml
.br
.sp
To convert a file with point locations (lon, lat, time) into a KML file with green circle symbols that
will go active at the specified time and stay active going forward, try
.br
.sp
awk '{print $1, $2, $3, "NaN"}' mypoints.txt | gmt2kml \fB\-Gf\fP green \fB\-Ft\fP > mytimepoints.kml
.SH "LIMITATIONS"
Google Earth has trouble displaying filled polygons across the Dateline.  For now you must manually break
any polygon crossing the dateline into a west and east polygon and plot them separately.
.SH "MAKING KMZ FILES"
Using the KMZ format is preferred as it takes less space.  KMZ is simply a KML file and any data files, icons, or images
referenced by the KML, contained in a zip archive.  One way to organize large data sets is to split them into groups
called Folders.  A Document can contain any number of folders.  Using scripts you can create a composite KML file
using the \fB\-K\fP, \fB\-O\fP options just like you do with GMT plots.  See \fB\-T\fP for switching between folders and
documents.
.SH "KML HIERARCHY"
\fBGMT\fP stores the different features in hierarchical folders,
by feature type (when using \fB\-O\fP, \fB\-K\fP or \fB\-T/\fP\fIfoldername\fP),
by input file (if not standard input), and
by line segment (using the name from the segment header, or \fB\-N\fP).
This makes it more easy in Google Earth to switch on or
off parts of the contents of the Document. The following is a crude example:
.sp
[ KML header information - not present if \fB\-O\fP was given ]
.br
<Document><name>GMT Data Document</name>
.br
    <Folder><name>Point Features</name>
.br
        <!--This level of folder is inserted only when using -O, -K>
.br
        <Folder><name>file1.dat</name>
.br
            <!--One folder for each input file (not when standard input)>
.br
            <Folder><name>Point Set 0</name>
.br
            <!--One folder per line segment>
.br
            <!--Points from the first line segment in file file1.dat go here>
.br
            <Folder><name>Point Set 1</name>
.br
            <!--Points from the second line segment in file file1.dat go here>
.br
        </Folder>
.br
    </Folder>
.br
    <Folder><name>Line Features</name>
.br
        <Folder><name>file1.dat</name>
.br
            <!--One folder for each input file (not when standard input)>
.br
            <Placemark><name>Line 0</name>
.br
                <!--Here goes the first line segment>
.br
            </Placemark>
.br
            <Placemark><name>Line 1</name>
.br
                <!--Here goes the second line segment>
.br
            </Placemark>
.br
        </Folder>
.br
    <Folder>
.br
</Document>
.br
[ KML trailer information - not present if \fB\-K\fP was given ]
.SH "SEGMENT INFORMATION"
\fBgmt2kml\fP will scan the segment headers for substrings of the form
\fB\-L\fP"\fIsome label\fP" [also see \fB\-N\fP discussion] and
\fB\-D\fP"\fIsome description\fP".  If present, these are parsed to supply
name and description tags for the current feature.
.br
.SH "SEE ALSO"
.IR gmtdefaults (1),
.IR GMT (1),
.IR img2google (1),
.IR kml2gmt (1),
.IR ps2raster (1)
