.TH PSMEGAPLOT 1 "1 Jan 2013" "GMT 4.5.9" "Generic Mapping Tools"
.SH NAME
psmegaplot \- To create poster-size \fIPostScript\fP plots from page-size plot
.SH SYNOPSIS
\fBpsmegaplot\fP \fIplotfile\fP \fB\-S\fP\fIscale\fP [ \fB\-C\fP ]
.SH DESCRIPTION
\fBpsmegaplot\fP reads a \fBGMT\fP-produced \fIPostScript\fP file and 'blows it up' by an arbitrary scale. The result is several
plots that make up the pieces in a jigsaw puzzle. Cut and paste these pieces to make a 'megaplot'.
.sp
.TP
\fIplotfile\fP
\fIPostScript\fP file as created by the \fBGMT\fP programs.
.TP
\fB\-S\fP
Multiply the x- and y-dimension by \fIscale\fP.  \fIscale\fP must be larger than 1.0.
.SH OPTIONS
No space between the option flag and the associated arguments.
.TP
\fB\-C\fP
Plot crop marks in each corner of every output page. [Default is no marks]
.SH EXAMPLES
To magnify a contour-map PostScript file 3 times, giving a total of 9 output pages to be pasted
together, use
.br
.sp
\fBpsmegaplot\fP hawaii_contour.ps \fB\-S\fP3 \fB\-C\fP > hawaii_contour_megaplot.ps
.SH BUGS
This program is unlikely to work on non-\fBGMT\fP-produced \fIPostScript\fP files
since it anticipates the structure of the file.  It also assumes that the
output media is Letter size.
.SH "SEE ALSO"
.IR GMT (1)
